{{- if and (not .Values.monitoring.enabled) .Values.grafanaAlloy.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ dig "istio" "injection" "enabled" .Values.grafana }}
{{- end }}
