{{- /* Create secret */ -}}
{{- if .Values.addons.grafanaAlloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.grafanaAlloy "name" "grafana-alloy" "defaults" (include "bigbang.defaults.grafana-alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.grafana-alloy" -}}

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

domain: {{ .Values.domain }}

{{- end }}