{{- $fluxSettingsMattermost := merge .Values.packages.addons.mattermost.flux .Values.flux -}}
{{- if .Values.packages.addons.mattermost.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/mattermost/values.yaml") . | sha256sum }}
spec:
  releaseName: mattermost
  targetNamespace: mattermost
  driftDetection:
    mode: disabled
  chart:
    spec:
      {{- if eq .Values.packages.addons.mattermost.sourceType "git" }}
      chart: {{ .Values.packages.addons.mattermost.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: mattermost
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.mattermost.helmRepo.chartName }}
      version: {{ .Values.packages.addons.mattermost.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.mattermost.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.mattermost.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.mattermost.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.mattermost.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsMattermost | nindent 2 }}

  {{- if .Values.packages.addons.mattermost.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.mattermost.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-mattermost-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: mattermost-operator
      namespace: {{ .Release.Namespace }}

    {{- if .Values.packages.addons.minioOperator.enabled }} 
    - name: minio-operator 
      namespace: {{ $.Release.Namespace }} 
    {{- end }}

    {{- if and .Values.packages.addons.mattermost.elasticsearch.enabled .Values.packages.addons.elasticsearchKibana.enabled }}
    - name: ek
      namespace: {{ $.Release.Namespace }}
    {{- end }}
{{- end }}
