{{- $fluxSettingsMinio := merge .Values.packages.addons.minio.flux .Values.flux -}}
{{- if .Values.packages.addons.minio.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/minio/values.yaml") . | sha256sum }}
spec:
  targetNamespace: minio
  driftDetection:
    mode: disabled
  chart:
    spec:
      {{- if eq .Values.packages.addons.minio.sourceType "git" }}
      chart: {{ .Values.packages.addons.minio.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: minio
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.minio.helmRepo.chartName }}
      version: {{ .Values.packages.addons.minio.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.minio.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.minio.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.minio.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.minio.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsMinio | nindent 2 }}
  
  {{- if .Values.packages.addons.minio.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.minio.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-minio-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-minio-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-minio-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
    - name: minio-operator
      namespace: {{ .Release.Namespace }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}      
{{- end }}
