# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Gateway API - Ambient Tests
templates:
  - templates/authservice/helmrelease.yaml
  - templates/authservice/values.yaml
  - templates/gateway-api/helmrelease.yaml
  - templates/gateway-api/gitrepository.yaml
  - templates/gateway-api/values.yaml
tests:
  - it: should render HelmRelease when ambient mode is enabled via ztunnel
    template: templates/gateway-api/helmrelease.yaml
    set:
      ztunnel:
        enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: HelmRelease
      - equal:
          path: metadata.name
          value: gateway-api

  - it: should render GitRepository when ambient mode is enabled via ztunnel
    template: templates/gateway-api/gitrepository.yaml
    set:
      ztunnel:
        enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: GitRepository
      - equal:
          path: metadata.name
          value: gateway-api

  - it: should render values Secret when ambient mode is enabled via ztunnel
    template: templates/gateway-api/values.yaml
    set:
      ztunnel:
        enabled: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Secret
      - equal:
          path: metadata.name
          value: RELEASE-NAME-gateway-api-values

  - it: should make ambient consumers wait for Gateway API CRDs
    template: templates/authservice/helmrelease.yaml
    set:
      ztunnel:
        enabled: true
      istiod:
        enabled: true
      addons:
        authservice:
          enabled: true
    asserts:
      - contains:
          path: spec.dependsOn
          content:
            name: gateway-api
            namespace: NAMESPACE
