{{- if and .Values.istioCore.enabled (not .Values.istioOperator.enabled) }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istioCore
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}