{{- $pkg := "istioCore" }}

{{- /* Create secret */ -}}
{{- if (get .Values $pkg).enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values $pkg) "name" ($pkg | kebabcase) "defaults" (include (printf "bigbang.defaults.%s" $pkg | kebabcase) .)) }}
{{- end }}

{{- define "bigbang.defaults.istio-core" -}}
createNamespace: true

enterprise: {{ .Values.istioCore.enterprise }}
imagePullPolicy: {{ .Values.imagePullPolicy }}

imagePullSecrets:
  - private-registry

istiod:
  networkPolicies:
    enabled: {{ .Values.networkPolicies.enabled }}
    controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

  monitoring:
    enabled: {{ .Values.monitoring.enabled }}
    
  {{- if or .Values.addons.authservice.enabled .Values.jaeger.enabled }}
  meshConfig:
    {{- if .Values.jaeger.enabled }}
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 10
        zipkin:
          address: "jaeger-collector.jaeger.svc:9411"
    {{- end }}
    {{- if .Values.addons.authservice.enabled }}
    extensionProviders:
      - name: "authservice"
        envoyExtAuthzGrpc:
          service: "authservice.authservice.svc.cluster.local"
          port: "10003"
    {{- end }}
  {{- end }}

{{- end }}
