# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Package - Istio Gateway - CA Cert Secret Tests
templates:
  - templates/istio-gateway/secret-ca.yaml
release:
  name: bb
tests:
  - it: should create a <credentialName>-cacert secret for a MUTUAL/OPTIONAL_MUTUAL server block
    set:
      addons.keycloak.enabled: true
    asserts:
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: public-cert-cacert
          namespace: istio-gateway
      - equal:
          path: type
          value: Opaque
      - isNotNull:
          path: data.cacert
        documentSelector:
          path: metadata.name
          value: public-cert-cacert

  - it: should not create a cacert secret when no gateway server uses MUTUAL/OPTIONAL_MUTUAL
    asserts:
      - hasDocuments:
          count: 0
