suite: Test Kyverno Policy Merge Logic (With Deduplication)

templates:
  - templates/kyverno-policies/kyverno-merged-policies.yaml

tests:
  - it: should merge namespaces by name and deduplicate pod entries
    set:
      kyvernoPolicies:
        policies:
          update-automountserviceaccounttokens:
            namespaces:
              - namespace: monitoring
                pods:
                  allow:
                    - test-monitoring
                    - grafana  # duplicate to test deduplication
                  deny:
                    - deny-monitoring
              - namespace: custom
                pods:
                  allow:
                    - custom-pod
                  deny:
                    - custom-deny

    asserts:
      # Merged and deduplicated 'allow' list for monitoring
      - equal:
          path: policies.update-automountserviceaccounttokens.namespaces[?(@.namespace=="monitoring")].pods.allow | [0]
          value: [ "grafana", "test-monitoring" ]

      # Deduplicated 'deny' list for monitoring
      - equal:
          path: policies.update-automountserviceaccounttokens.namespaces[?(@.namespace=="monitoring")].pods.deny | [0]
          value: [ "deny-monitoring" ]

      # Custom namespace from overlay
      - equal:
          path: policies.update-automountserviceaccounttokens.namespaces[?(@.namespace=="custom")].pods.allow | [0]
          value: [ "custom-pod" ]

      - equal:
          path: policies.update-automountserviceaccounttokens.namespaces[?(@.namespace=="custom")].pods.deny | [0]
          value: [ "custom-deny" ]
