{{- if .Values.kiali.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $istioInjection := (and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.kiali) "enabled")) }}
apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    {{- if $istioInjection }}
    istio-injection: {{ ternary "enabled" "disabled" (and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.alloy) "enabled")) }}
    {{- else }}
    istio.io/dataplane-mode: ambient
    {{- end }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}