{{- if .Values.kiali.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
  {{- if .Values.istioZtunnel.enabled }}
    istio.io/dataplane-mode: ambient
  {{- else }}
    istio-injection: {{ ternary "enabled" "disabled" (and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.kiali) "enabled")) }}
  {{- end }}
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
