{{- if ((.Values.gatekeeper).enabled) }}
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: gatekeeper
    name: gatekeeper-disallow-auto-mount-service-account-token-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: disallow-auto-mount-service-account-token
      ruleNames:
      - disallow-auto-mount-service-account-token
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          names:
          - gatekeeper-audit*
          - gatekeeper-controller-manager*
          namespaces:
          - gatekeeper-system
{{- end }}