{{- if or (and .Values.addons.headlamp.enabled .Values.headlamp.config.oidc.clientId) (dig "headlamp" "clientId" false .Values.headlamp.config.oidc) }}
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-sso
  namespace: headlamp
type: kubernetes.io/opaque
stringData:
  {{- if (dig "headlamp" "clientId" false .Values.headlamp.config.oidc) }}
  client_id: {{ (dig "headlamp" "clientId" false .Values.headlamp.config.oidc) }}
  {{- else if .Values.headlamp.config.oidc.clientId }}
  client_id: {{ .Values.headlamp.config.oidc.clientId }}
  {{- end }}
  {{- if (dig "headlamp" "clientSecret" false .Values.headlamp.config.oidc) }}
  client_secret: {{ (dig "headlamp" "clientSecret" false .Values.headlamp.config.oidc) }}
  {{- else if .Values.headlamp.config.oidc.clientSecret }}
  client_secret: {{ .Values.headlamp.config.oidc.clientSecret }}
  {{- end }}
{{- end }}
