{{- if or (and .Values.headlamp.enabled .Values.headlamp.sso.enabled .Values.headlamp.sso.headlamp.client_id) (and .Values.headlamp.sso.enabled (dig "headlamp" "client_id" false .Values.headlamp.sso)) }}
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-sso
  namespace: headlamp
type: kubernetes.io/opaque
stringData:
  {{- if (dig "headlamp" "client_id" false .Values.headlamp.sso) }}
  client_id: {{ (dig "headlamp" "client_id" false .Values.headlamp.sso) }}
  {{- else if .Values.headlamp.sso.headlamp.client_id }}
  client_id: {{ .Values.headlamp.sso.headlamp.client_id }}
  {{- end }}
  {{- if (dig "headlamp" "client_secret" false .Values.headlamp.sso) }}
  client_secret: {{ (dig "headlamp" "client_secret" false .Values.headlamp.sso) }}
  {{- else if .Values.headlamp.sso.headlamp.client_secret }}
  client_secret: {{ .Values.headlamp.sso.headlamp.client_secret }}
  {{- end }}
{{- end }}

