{{- if and .Values.addons.bbctl.enabled .Values.loki.enabled .Values.promtail.enabled .Values.monitoring.enabled .Values.grafana.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: bbctl
  labels:
    app.kubernetes.io/name: bbctl
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
