{{- $fluxSettingskyverno := merge .Values.packages.core.kyverno.flux .Values.flux -}}
{{- if or .Values.packages.core.kyverno.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.addons.kyvernoReporter.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/kyverno/values.yaml") . | sha256sum }}
spec:
  targetNamespace: kyverno
  chart:
    spec:
      {{- if eq .Values.packages.core.kyverno.sourceType "git" }}
      chart: {{ .Values.packages.core.kyverno.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: kyverno
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.core.kyverno.helmRepo.chartName }}
      version: {{ .Values.packages.core.kyverno.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.core.kyverno.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.core.kyverno.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.core.kyverno.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.core.kyverno.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingskyverno | nindent 2 }}

  {{- if .Values.packages.core.kyverno.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.core.kyverno.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-kyverno-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-kyverno-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-kyverno-values
      kind: Secret
      valuesKey: "overlays"
  {{- if .Values.packages.addons.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
