{{- if or .Values.packages.core.kyverno.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.addons.kyvernoReporter.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: disabled
  name: kyverno
{{- end }}