{{- /* Used for creating values to use for Helm wrapper and package Helm charts. */ -}}
{{- range $pkgKey, $vals := .Values.packages -}}
{{- if and (dig "enabled" true $vals) (dig "wrapper" "enabled" false $vals) -}}
{{- $pkg := include "resourceName" $pkgKey -}}
{{- $istioEnabled := eq (include "istioEnabled" $) "true" -}}
{{- $istioHardened := dig "hardened" "enabled" false $.Values.istiod.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pkg }}-wrapper-values
  namespace: {{ if dig "helmRelease" "namespace" nil (index $.Values.packages $pkgKey) }}
               {{ dig "helmRelease" "namespace" "" (index $.Values.packages $pkgKey) }}
             {{ else }}
               {{ default (dig "namespace" "name" $pkg $vals) "" }}
             {{ end }}
type: Opaque
stringData:
  package-values.yaml: |
    {{ toYaml $vals.wrapper.values | nindent 4 }}
  values.yaml: |
    istio:
      enabled: {{ $istioEnabled }}
      ambient:
        enabled: {{ include "ambientEnabled" $ }}
      sidecar:
        enabled: {{ $istioHardened }}
      authorizationPolicies:
        enabled: {{ $istioHardened }}
        generateFromNetpol: {{ $istioHardened }}
    networkPolicies:
      hbonePortInjection:
        enabled: {{ include "ambientEnabled" $ }}
{{- pick $.Values.networkPolicies "enabled" "hbonePortInjection" "prependReleaseName" "defaultsAsHooks" "egress" "ingress" "additionalPolicies" "additional" | toYaml | nindent 6 }}
---
{{ end -}}
{{- end -}}
