# Refer to https://github.com/tcort/markdown-link-check?tab=readme-ov-file#config-file-format for details
# projectBaseUrl: ${workspaceFolder}
ignorePatterns:
  # ignore specific links in the change log
  - pattern: "https://docs.anchore.com/current/docs/overview/requirements/"
# replacementPatterns:
#   - pattern: ^.attachments
#     replacement: file://some/conventional/folder/.attachments
#   - pattern: ^/
#     replacement: '{{BASEURL}}/'
#   - pattern: '%20'
#     replacement: '-'
#     global: true
#   - pattern: images/(?<filename>.*)
#     replacement: assets/$<filename>
# httpHeaders:
#   - urls:
#       - https://example.com
#     headers:
#       Authorization: Basic Zm9vOmJhcg==
#       Foo: Bar
# timeout: 20s
# retryOn429: true
# retryCount: 2
# fallbackRetryDelay: 60s
# aliveStatusCodes:
#   - 200
#   - 206
#   - 429

