apiVersion: v1
kind: PackageCatalog
metadata:
  name: Big Bang Core
packages:
- name: Loki # A display name for any UI purposes that may arise later on
  id: loki # The actual key for the package that will be used in the values overlay
  version: 6.29.0-bb.1
  sources:
    helm: # Keep the possibility of additional sources like Kustomizations or raw manifests in the future
      oci: oci://registry1.dso.mil/bigbang/loki
      git: https://repo1.dso.mil/big-bang/product/packages/loki.git
