{{- $fluxSettingsGitlabRunner := merge .Values.packages.addons.gitlabRunner.flux .Values.flux -}}
{{- if .Values.packages.addons.gitlabRunner.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/gitlab-runner/values.yaml") . | sha256sum }}
spec:
  targetNamespace: gitlab-runner
  releaseName: gitlab-runner
  chart:
    spec:
      {{- if eq .Values.packages.addons.gitlabRunner.sourceType "git" }}
      chart: {{ .Values.packages.addons.gitlabRunner.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: gitlab-runner
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.gitlabRunner.helmRepo.chartName }}
      version: {{ .Values.packages.addons.gitlabRunner.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.gitlabRunner.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.gitlabRunner.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.gitlabRunner.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.gitlabRunner.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsGitlabRunner | nindent 2 }}

  {{- if .Values.packages.addons.gitlabRunner.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.gitlabRunner.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gitlab-runner-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.packages.addons.gatekeeper.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.addons.monitoring.enabled .Values.packages.addons.gitlab.enabled }}
  dependsOn:
    {{- if .Values.packages.addons.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyverno.enabled }}
    - name: kyverno
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.gitlab.enabled }}
    - name: gitlab
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
