{{- $fluxSettingsFluentbit := merge .Values.packages.addons.fluentbit.flux .Values.flux -}}
{{- if .Values.packages.addons.fluentbit.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/fluentbit/values.yaml") . | sha256sum }}
spec:
  driftDetection:
    mode: warn
  targetNamespace: fluentbit
  releaseName: fluentbit
  chart:
    spec:
      {{- if eq .Values.packages.addons.fluentbit.sourceType "git" }}
      chart: {{ .Values.packages.addons.fluentbit.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: fluentbit
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.fluentbit.helmRepo.chartName }}
      version: {{ .Values.packages.addons.fluentbit.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.fluentbit.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.fluentbit.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.fluentbit.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.fluentbit.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsFluentbit | nindent 2 }}

  {{- if .Values.packages.addons.fluentbit.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.fluentbit.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-fluentbit-values
      kind: Secret
      valuesKey: "overlays"

  {{/* To support a "standalone" fluentbit for shipping to central location we conditionally depend on logging enabled */}}
  {{- if or .Values.packages.addons.elasticsearchKibana.enabled .Values.packages.addons.gatekeeper.enabled .Values.packages.core.istio.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.core.kyverno.enabled .Values.packages.addons.monitoring.enabled }}
  dependsOn:
    {{- if .Values.packages.addons.elasticsearchKibana.enabled }}
    - name: ek
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if  .Values.packages.addons.loki.enabled }}
    - name: loki
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyverno.enabled }}
    - name: kyverno
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
