{{- if .Values.istio3.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-base-managed: Reconcile
    istio-injection: disabled
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
