{{- if .Values.istio3.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-base-managed: Reconcile
    istio-injection: disabled
    app.kubernetes.io/name: istio3
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- if or .Values.istioGatewayPublic.enabled .Values.istioGatewayPassthrough.enabled .Values.istio3Gateways.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    istio-gateway-managed: Reconcile
    istio-injection: enabled
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
{{- end }}
