{{- if .Values.neuvector.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
  labels:
    app.kubernetes.io/name: neuvector
    app.kubernetes.io/component: "sandbox"
    {{- include "commonLabels" . | nindent 4}}
    {{- if .Values.neuvector.istio.ambient }}
    istio.io/dataplane-mode: ambient
    {{- else }}
    istio-injection: {{ ternary "enabled" "disabled" (and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.neuvector) "enabled")) }}
    {{- end }}
{{- end }}