{{- $istioEnabled := eq (include "istioEnabled" .) "true" -}}
{{- $istioHardened := dig "hardened" "enabled" false .Values.istiod.values -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-platform-values
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
{{- .Values | toYaml | nindent 4 }}
  common.yaml: |
    global:
      domain: {{ .Values.domain }}
      monitoring:
        enabled: {{ .Values.monitoring.enabled }}
      ztunnel:
        enabled: {{ .Values.ztunnel.enabled }}
      ambient: {{ .Values.ambient }}
    bb-common:
      istio:
        enabled: {{ $istioEnabled }}
        sidecar:
          enabled: {{ $istioHardened }}
        authorizationPolicies:
          enabled: {{ $istioHardened }}
          generateFromNetpol: {{ $istioHardened }}
      
      networkPolicies:
{{- pick .Values.networkPolicies "enabled" "hbonePortInjection" "prependReleaseName" "defaultsAsHooks" "egress" "ingress" "additionalPolicies" "additional" | toYaml | nindent 8 }}
