{{- if .Values.addons.backstage.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.backstage "name" "backstage" "defaults" (include "bigbang.defaults.backstage" .)) }}
{{- end }}

{{- define "bigbang.defaults.backstage" -}}

{{- $istioInjection := (and (eq (dig "istio" "injection" "enabled" .Values.addons.backstage) "enabled") .Values.istio.enabled) }}

# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

istio:
  enabled: {{ include "istioEnabled" . }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.addons.backstage.values)
      (dig "hardened" "enabled" false .Values.istio.values)
    }}
  injection: {{ dig "istio" "injection" "enabled" .Values.addons.backstage }}
  backstage:
    gateways:
    - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.addons.backstage.ingress.gateway }}

{{- if .Values.addons.backstage.sso.enabled }}
backstage:
  backstage:
    appConfig:
      auth:
        session:
          secret: "XxNl2b+/hGH7w7RJk8c5LXNOBh6+kzysxgYXlMK5Pgo="
        environment: development
        providers:
          guest:
            dangerouslyAllowOutsideDevelopment: false
          keycloak:
            development:
              metadataUrl: "{{ .Values.sso.url }}/.well-known/openid-configuration"
              clientId: "{{ .Values.addons.backstage.sso.client_id }}"
              clientSecret: "{{ .Values.addons.backstage.sso.client_secret }}"
              prompt: auto

{{- end }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}


{{- end -}}

