{{- if and .Values.packages.core.istioCore.enabled .Values.packages.core.istioGateway.enabled }}
{{- range $name, $gw := .Values.packages.core.istioGateway.values.gateways }} 
{{- if dig "tls" false $gw }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-cert
  namespace: istio-gateway
  labels:
    app.kubernetes.io/name: istio-gateway-{{ $name }}
    app.kubernetes.io/component: core
    {{- include "commonLabels" $ | nindent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ $gw.tls.cert | b64enc }}
  tls.key: {{ $gw.tls.key | b64enc }}
  {{- if $gw.tls.ca }}
  ca.crt: {{ $gw.tls.ca | b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
