{{- if and .Values.packages.addons.monitoring.enabled (not ( .Values.packages.addons.thanos.objectStorage.endpoint | empty)) }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-objstore-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: {{ .Values.packages.addons.thanos.objectStorage.bucket }}
      endpoint: {{ .Values.packages.addons.thanos.objectStorage.endpoint }}
      access_key: {{ .Values.packages.addons.thanos.objectStorage.accessKey }}
      secret_key: {{ .Values.packages.addons.thanos.objectStorage.accessSecret }}
      insecure: {{ .Values.packages.addons.thanos.objectStorage.insecure }}
{{- end }}
