{{- $pkg := "ztunnel" }}

{{- /* Create secret */ -}}
{{- if or .Values.ztunnel.enabled .Values.ambient }}
{{- include "values-secret" (dict "root" $ "package" (get .Values $pkg) "name" "ztunnel" "defaults" (include "bigbang.defaults.ztunnel" .)) }}
{{- end }}

{{- define "bigbang.defaults.ztunnel" -}}
upstream:
  ambient:
    enabled: {{ .Values.ambient }}
  global:
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    {{- include "secretsImagePullSecrets" . | nindent 4 }}
{{- end }}
