{{- $gitCredsSecretDict := dict
  "name" "garage"
  "targetScope" .Values.addons.garage
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
