{{- if and (eq .Values.addons.garage.sourceType "git") (not .Values.offline) .Values.addons.garage.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "garage" "gitCredsName" "garage" "git" .Values.addons.garage.git "component" "core" "root" .) }}
{{- end }}
