{{- $fluxSettingsGarage := mergeOverwrite (deepCopy .Values.flux) (default (dict) .Values.addons.garage.flux) -}}
{{- if .Values.addons.garage.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $metricScrapingEnabled := eq (include "metricScrapingEnabled" .) "true" }}
{{- $ambientEnabled := eq (include "ambientEnabled" .) "true" }}
{{- $garageSidecarInjected := and $istioEnabled (not $ambientEnabled) (eq (dig "istio" "injection" "enabled" .Values.addons.garage) "enabled") }}
{{- $garageInjectionState := ternary "enabled" "disabled" $garageSidecarInjected }}
{{- $installMetricsPostRenderer := and $metricScrapingEnabled $istioEnabled }}
{{- $installServiceMonitorJobLabelPostRenderer := $metricScrapingEnabled }}
{{- $installServiceMonitorPostRenderer := and $metricScrapingEnabled $garageSidecarInjected (eq (dig "bb-common" "istio" "mtls" "mode" "STRICT" .Values.addons.garage.values) "STRICT") }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/component: "application-utilities"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/garage/values.yaml") . | sha256sum }}
spec:
  targetNamespace: garage
  {{- include "bigbang.helmRelease.chartSpec" (dict "name" "garage" "package" .Values.addons.garage "root" . "emitReleaseName" true) | nindent 2 }}

  {{- toYaml $fluxSettingsGarage | nindent 2 }}

  postRenderers:
  {{- if $installMetricsPostRenderer }}
  {{ include "garage.metricsServicePostRenderer" . | nindent 2 }}
  {{- end }}
  {{- if $installServiceMonitorJobLabelPostRenderer }}
  {{ include "garage.serviceMonitorJobLabelPostRenderer" . | nindent 2 }}
  {{- end }}
  {{- if $installServiceMonitorPostRenderer }}
  {{ include "garage.serviceMonitorPostRenderer" . | nindent 2 }}
  {{- end }}
  {{ include "garage.sidecarRolloutPostRenderer" (dict "state" $garageInjectionState) | nindent 2 }}
  {{- with .Values.addons.garage.postRenderers }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- include "bigbang.helmRelease.valuesFrom" (dict "name" "garage" "root" .) | nindent 2 }}

  {{- if or $istioEnabled .Values.kyvernoPolicies.enabled .Values.monitoring.enabled .Values.alloy.enabled }}
  dependsOn:
  {{- if $istioEnabled }}
    {{- include "istioHelmReleases" . | nindent 4 }}
  {{- end }}
  {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.alloy.enabled }}
    - name: alloy
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
