{{- if .Values.addons.garage.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: garage
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
