{{- $fluxSettingsJaeger := merge .Values.packages.addons.jaeger.flux .Values.flux -}}
{{- if .Values.packages.addons.jaeger.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/jaeger/values.yaml") . | sha256sum }}
spec:
  driftDetection:
    mode: warn
  targetNamespace: jaeger
  chart:
    spec:
      {{- if eq .Values.packages.addons.jaeger.sourceType "git" }}
      chart: {{ .Values.packages.addons.jaeger.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.jaeger.helmRepo.chartName }}
      version: {{ .Values.packages.addons.jaeger.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.jaeger.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.jaeger.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.jaeger.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.jaeger.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsJaeger | nindent 2 }}

  {{- if .Values.packages.addons.jaeger.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.jaeger.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "overlays"

  {{ if or (include "istioEnabled" .) .Values.packages.addons.monitoring.enabled .Values.packages.addons.jaeger.sso.enabled .Values.packages.addons.elasticsearchKibana.enabled }}
  dependsOn:
  {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
    {{- if .Values.packages.core.istioCore.enabled }}
    - name: istio-core
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.addons.jaeger.sso.enabled }}
    - name: authservice
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.addons.elasticsearchKibana.enabled }}
    - name: ek
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
