{{- if .Values.packages.addons.jaeger.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.jaeger "name" "jaeger" "defaults" (include "bigbang.defaults.jaeger" .)) }}
{{- end }}

{{- define "bigbang.defaults.jaeger" -}}
imagePullSecrets:
  - name: private-registry

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

istio:
  enabled: {{ include "istioEnabled" . }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.jaeger.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  jaeger:
    enabled: {{ include "istioEnabled" . }}
    gateways:
    - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.packages.addons.jaeger.ingress.gateway }}

{{- if include "istioEnabled" . }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}
  # conditional passes only for default istio: enabled, mTLS: SCRICT
  {{- if and (include "istioEnabled" . ) (eq (dig "istio" "mtls" "mode" "STRICT" .Values.packages.addons.jaeger.values) "STRICT") }}
  serviceMonitor:
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
  {{- end }}

elasticsearch:
  enabled: {{ .Values.packages.addons.elasticsearchKibana.enabled }}

sso:
  enabled: {{ .Values.packages.addons.jaeger.sso.enabled }}


{{- if or .Values.packages.addons.jaeger.sso.enabled (include "istioEnabled" .) .Values.packages.addons.kiali.enabled }}
jaeger:
  spec:
    {{- if or .Values.packages.addons.jaeger.sso.enabled (include "istioEnabled" .) }}
    {{- $jaegerAuthserviceKey := (dig "selector" "key" "protect" .Values.packages.addons.authservice.values) }}
    {{- $jaegerAuthserviceValue := (dig "selector" "value" "keycloak" .Values.packages.addons.authservice.values) }}
    allInOne:
      {{- if .Values.packages.addons.jaeger.sso.enabled }}
      labels:
        {{ $jaegerAuthserviceKey }}: {{ $jaegerAuthserviceValue }}
      {{- end }}
      {{- if include "istioEnabled" . }}
      annotations:
        {{ include "istioAnnotation" . }}
      {{- end }}
    query:
      {{- if .Values.packages.addons.jaeger.sso.enabled }}
      labels:
        {{ $jaegerAuthserviceKey }}: {{ $jaegerAuthserviceValue }}
      {{- end }}
      {{- if include "istioEnabled" . }}
      annotations:
        {{ include "istioAnnotation" . }}
      {{- end }}
    {{- end }}
    {{- if include "istioEnabled" . }}
    agent:
      annotations:
        {{ include "istioAnnotation" . }}
    ingester:
      annotations:
        {{ include "istioAnnotation" . }}
    collector:
      annotations:
        {{ include "istioAnnotation" . }}
    {{- end }}
{{- end }}
openshift:
  enabled: {{ .Values.openshift }}
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  istioNamespaceSelector:
  {{ include "istioNamespaceSelector" . | nindent 4 }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  ingressLabels:
    {{- $gateway := default "public" .Values.packages.addons.jaeger.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}

webhookCertGen:
  image:
    pullPolicy: {{ .Values.imagePullPolicy }}
  cleanupProxy:
    image:
      pullPolicy: {{ .Values.imagePullPolicy }}
{{- end -}}
