{{- if .Values.packages.addons.sonarqube.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.sonarqube "name" "sonarqube" "defaults" (include "bigbang.defaults.sonarqube" .)) }}
{{- end }}

{{- define "bigbang.defaults.sonarqube" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

# Define variables to help with conditionals later
{{- $istioInjection := (and (eq (dig "istio" "injection" "enabled" .Values.packages.addons.sonarqube) "enabled") .Values.packages.core.istio.enabled) }}

OpenShift:
  enabled: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.sonarqube.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  sonarqube:
    gateways:
    - istio-system/{{ default "public" .Values.packages.addons.sonarqube.ingress.gateway }}
  injection: {{ dig "istio" "injection" "enabled" .Values.packages.addons.sonarqube }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  istioNamespaceSelector:
  {{ include "istioNamespaceSelector" . | nindent 4 }}
  ingressLabels:
    {{- $gateway := default "public" .Values.packages.addons.sonarqube.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}

image:
  pullPolicy: {{ .Values.imagePullPolicy }}
  pullSecret: private-registry

{{- if $istioInjection }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

{{- if .Values.packages.addons.sonarqube.sso.enabled }}
sonarProperties:
  sonar.auth.saml.enabled: {{ .Values.packages.addons.sonarqube.sso.enabled }}
  sonar.core.serverBaseURL: https://sonarqube.{{ $domainName }}
  sonar.auth.saml.applicationId: {{ .Values.packages.addons.sonarqube.sso.client_id }}
  sonar.auth.saml.providerName: {{ coalesce .Values.packages.addons.sonarqube.sso.provider_name .Values.packages.addons.sonarqube.sso.label .Values.sso.name }}
  sonar.auth.saml.providerId: {{ include "sso.url" . }}
  sonar.auth.saml.loginUrl: {{ include "sso.saml.service" . }}
  sonar.auth.saml.certificate.secured: {{ default (include "sso.saml.cert" .) .Values.packages.addons.sonarqube.sso.certificate }}
  sonar.auth.saml.user.login: {{ .Values.packages.addons.sonarqube.sso.login | default "login" }}
  sonar.auth.saml.user.name: {{ .Values.packages.addons.sonarqube.sso.name | default "name" }}
  sonar.auth.saml.user.email: {{ .Values.packages.addons.sonarqube.sso.email | default "email" }}
  {{- if .Values.packages.addons.sonarqube.sso.group }}
  sonar.auth.saml.group.name: {{ .Values.packages.addons.sonarqube.sso.group }}
  {{- end }}
{{- end }}

{{- with .Values.packages.addons.sonarqube.database }}
  {{- if and .host .username .password .database .port }}
# External Postgres config
jdbcOverwrite:
  enable: true
  jdbcUrl: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .database }}?socketTimeout=1500"
  jdbcUsername: {{ .username }}
  jdbcSecretName: sonarqube-db-secret
  jdbcSecretPasswordKey: postgresql-password
postgresql:
  # Use external database
  enabled: false
  {{- else }}
postgresql:
  {{- if or $istioInjection $.Values.packages.addons.kiali.enabled}}
  master:
    {{- if $istioInjection }}
    podAnnotations:
      {{ include "istioAnnotation" $ }}
    {{- end }}
  slave:
    {{- if $istioInjection }}
    podAnnotations:
      {{ include "istioAnnotation" $ }}
    {{- end }}
  {{- end }}
  # Use internal database, defaults are fine
  enabled: true
  service:
    port: {{ .port }}
  {{- end }}
{{- end }}
{{- end -}}

