{{- $fluxSettingsVelero := merge .Values.packages.addons.velero.flux .Values.flux -}}
{{- if .Values.packages.addons.velero.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: "cluster-utilities"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/velero/values.yaml") . | sha256sum }}
spec:
  targetNamespace: velero
  driftDetection:
    mode: warn
  chart:
    spec:
      {{- if eq .Values.packages.addons.velero.sourceType "git" }}
      chart: {{ .Values.packages.addons.velero.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: velero
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.velero.helmRepo.chartName }}
      version: {{ .Values.packages.addons.velero.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.velero.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.velero.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.velero.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.velero.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsVelero | nindent 2 }}
  
  {{- if .Values.packages.addons.velero.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.velero.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-velero-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-velero-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-velero-values
      kind: Secret
      valuesKey: "overlays"
  {{- if or .Values.packages.core.istio.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.addons.monitoring.enabled }}
  dependsOn:
    {{- if .Values.packages.core.istio.enabled }}  
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyvernoPolicies.enabled }}  
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
