{{- if .Values.packages.addons.velero.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.velero "name" "velero" "defaults" (include "bigbang.defaults.velero" .)) }}
{{- end }}

{{- define "bigbang.defaults.velero" -}}

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.velero.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}

domain: {{ .Values.domain }}

{{- if .Values.packages.core.istio.enabled }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

{{- if .Values.packages.addons.monitoring.enabled }}
metrics:
  enabled: true
  scrapeInterval: 30s
  scrapeTimeout: 10s
  service:
    annotations: {}
    labels: {}
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    {{- if and .Values.packages.core.istio.enabled (eq (dig "istio" "mtls" "mode" "STRICT" .Values.packages.addons.velero.values) "STRICT") }}
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target
    {{- end }}
  prometheusRule:
    enabled: true
{{- end }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

openshift: {{ .Values.openshift }}

imagePullSecrets:
- name: private-registry

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

{{- if eq (len .Values.packages.addons.velero.plugins) 0 }}{{- fail "At least one plugin in '.Values.packages.addons.velero.plugins' required. Supported values: aws, azure, csi" }}{{- end }}
plugins:
{{- range .Values.packages.addons.velero.plugins }}
{{- if eq . "aws" }}
  aws:
    enabled: true
{{- end }}
{{- if eq . "azure" }}
  azure:
    enabled: true
{{- end }}
{{- if eq . "csi" }}
  csi:
    enabled: true
configuration:
  features: EnableCSI
{{- end }}
{{- end }}

{{- end -}}
