{{- $fluxSettingsArgo := merge .Values.packages.addons.argocd.flux .Values.flux -}}
{{- if .Values.packages.addons.argocd.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/argocd/values.yaml") . | sha256sum }}
spec:
  targetNamespace: argocd
  chart:
    spec:
      {{- if eq .Values.packages.addons.argocd.sourceType "git" }}
      chart: {{ .Values.packages.addons.argocd.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: argocd
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.argocd.helmRepo.chartName }}
      version: {{ .Values.packages.addons.argocd.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.argocd.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.argocd.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.argocd.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.argocd.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsArgo | nindent 2 }}

  {{- if .Values.packages.addons.argocd.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.argocd.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-argocd-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.packages.addons.monitoring.enabled .Values.packages.core.istio.enabled }}
  dependsOn:
  {{- if .Values.packages.core.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace}}
  {{- end}}
  {{- if .Values.packages.addons.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
