{{- if .Values.addons.keycloak.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{ $name := "keycloak" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name }}
  labels:
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: keycloak-waypoint
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: "security-tools"
    {{- include "commonLabels" . | nindent 4 }}
{{- end }}
