{{- $fluxSettingsMetrics := merge .Values.packages.addons.metricsServerServer.flux .Values.flux -}}
{{- $enableFlag := .Values.packages.addons.metricsServerServer.enabled | toString }}
{{- $existingMetricsApi := (.Capabilities.APIVersions.Has "metrics.k8s.io/v1beta1") }}
{{- $existingMetricsHelmRelease := (lookup "helm.toolkit.fluxcd.io/v2" "HelmRelease" "bigbang" "metrics-server") }}
{{- if or ( eq $enableFlag "true") (and (eq $enableFlag "auto") (or (not $existingMetricsApi) $existingMetricsHelmRelease)) }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/component: "cluster-utilities"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/metrics-server/values.yaml") . | sha256sum }}
spec:
  driftDetection:
    mode: warn
  releaseName: metrics-server
  targetNamespace: metrics-server
  chart:
    spec:
      {{- if eq .Values.packages.addons.metricsServerServer.sourceType "git" }}
      chart: {{ .Values.packages.addons.metricsServerServer.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: metrics-server
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.metricsServerServer.helmRepo.chartName }}
      version: {{ .Values.packages.addons.metricsServerServer.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.metricsServerServer.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.metricsServerServer.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.metricsServerServer.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.metricsServerServer.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsMetrics | nindent 2 }}

  {{- if .Values.packages.addons.metricsServerServer.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.metricsServerServer.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-metrics-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-metrics-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-metrics-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.packages.core.istio.enabled .Values.packages.addons.monitoring.enabled }}
  dependsOn:
    {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
