{{- if and (or .Values.istio.enabled .Values.istio3.enabled) (or .Values.addons.authservice.enabled (and .Values.monitoring.enabled .Values.monitoring.sso.enabled) (and .Values.jaeger.enabled .Values.jaeger.sso.enabled) (and .Values.tempo.enabled .Values.tempo.sso.enabled)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: authservice
  labels:
    istio-injection: {{ ternary "enabled" "disabled" (and (or .Values.istio.enabled .Values.istio3.enabled) (eq (dig "istio" "injection" "enabled" .Values.addons.authservice) "enabled")) }}
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}

