{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- if and $istioEnabled (or .Values.addons.authservice.enabled (and .Values.monitoring.enabled .Values.monitoring.sso.enabled) (and .Values.tempo.enabled .Values.tempo.sso.enabled)) }}
{{- $istioInjection := and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.kiali) "enabled") }}
apiVersion: v1
kind: Namespace
metadata:
  name: authservice
  labels:
    {{- if and $istioEnabled .Values.ztunnel.enabled }}
    istio.io/dataplane-mode: ambient
    {{- else if $istioInjection }}
    istio-injection: enabled
    {{- end }}
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}

