{{- if and (not .Values.monitoring.enabled) (not .Values.grafana.enabled ) .Values.addons.mimir.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mimir
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}

