{{- /* Create secret */ -}}
{{- if .Values.addons.mimir.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.mimir "name" "mimir" "defaults" (include "bigbang.defaults.mimir" .)) }}
{{- end }}

{{- define "bigbang.defaults.mimir" -}}
{{- $minioEnabled := (.Values.addons.minio.enabled) }}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.monitoring.values)
      (dig "istio" "hardened" "enabled" false .Values.addons.authservice.values)
      (dig "hardened" "enabled" false .Values.istio.values)
      (dig "istio" "hardened" "enabled" false .Values.grafana.values)
      (dig "istio" "hardened" "enabled" false .Values.loki.values)
      (dig "istio" "hardened" "enabled" false .Values.eckOperator.values)
      (dig "istio" "hardened" "enabled" false .Values.elasticsearchKibana.values)
      (dig "istio" "hardened" "enabled" false .Values.addons.mimir.values)
    }}

mimir_distributed:
  {{- if .Values.istio.enabled }}
  query_scheduler:
    enabled: false
  {{- end }}
  mimir:
    {{- if not $minioEnabled }}
    structuredConfig:
        blocks_storage:
          backend: filesystem
    {{- end }}
{{- end }}
