{{- if .Values.addons.tetragon.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/component: "addon"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}