{{- if .Values.packages.addons.externalSecrets.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    meta.helm.sh/release-namespace: bigbang
    meta.helm.sh/release-name: bigbang
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.externalSecrets) "enabled")) }}
  name: external-secrets
{{- end }}
