{{- if .Values.packages.addons.externalSecrets.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.externalSecrets "name" "external-secrets" "defaults" (include "bigbang.defaults.external-secrets" .)) }}
{{- end }}

{{- define "bigbang.defaults.external-secrets" -}}

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

{{- if .Values.packages.core.istio.enabled }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.externalSecrets.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}

openshift: {{ .Values.openshift }}
{{- end -}}
