
{{- if and ((.Values.velero).enabled) (.Values.kyverno).enabled }}
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: velero
    name: velero-add-default-capability-drop-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: add-default-capability-drop
      ruleNames:
      - add-default-capability-drop
    match:
      any:
      - resources:
          names:
          - velero-backup-restore-test*
          namespaces:
          - velero
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: velero
    name: velero-require-drop-all-capabilities-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-drop-all-capabilities
      ruleNames:
      - require-drop-all-capabilities
    match:
      any:
      - resources:
          names:
          - velero-backup-restore-test*
          namespaces:
          - velero
{{- end }}