{{- if and (ne .Values.addons.gitlab.railsSecret "") .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rails-secret-bb
  namespace: gitlab
type: Opaque
stringData:
  secrets.yml: |-
    {{- .Values.addons.gitlab.railsSecret | nindent 4 }}
{{- end }}
