{{- if and (ne .Values.addons.gitlab.railsSecret "") .Values.addons.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rails-secret-bb
  namespace: gitlab
type: Opaque
data:
  secrets.yml: {{ .Values.addons.gitlab.railsSecret | b64enc }}
{{- end }}
