{{- $fluxSettingsMimir := merge .Values.packages.addons.mimir.flux .Values.flux -}}
{{- if .Values.packages.addons.mimir.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mimir
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/mimir/values.yaml") . | sha256sum }}
spec:
  targetNamespace: mimir
  chart:
    spec:
      {{- if eq .Values.packages.addons.mimir.sourceType "git" }}
      chart: {{ .Values.packages.addons.mimir.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: mimir
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.mimir.helmRepo.chartName }}
      version: {{ .Values.packages.addons.mimir.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.mimir.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.mimir.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.mimir.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.mimir.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsMimir | nindent 2 }}
  {{- if or .Values.packages.addons.mimir.postRenderers .Values.packages.core.istio.enabled }}
  postRenderers:
  {{- if .Values.packages.core.istio.enabled }}
  {{ include "mimir.istioPostRenderers" . | nindent 2 }}
  {{- end }}
  {{- with .Values.packages.addons.mimir.postRenderers }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-mimir-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-mimir-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-mimir-values
      kind: Secret
      valuesKey: "overlays"

  # TODO: DRY this up
  {{- if or .Values.packages.core.istio.enabled .Values.packages.core.kyvernoPolicies.enabled .Values.packages.addons.monitoring.enabled .Values.packages.addons.minioOperator.enabled }}
  dependsOn:
  {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.core.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.addons.minioOperator.enabled }}
    - name: minio-operator
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
