{{- $fluxSettingsGatekeeper := merge .Values.packages.addons.gatekeeper.flux .Values.flux -}}
{{- if or .Values.packages.addons.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/gatekeeper/values.yaml") . | sha256sum }}
spec:
  # Use a non-persistent client to allow for Gatekeeper CRD *magic*
  persistentClient: false
  targetNamespace: gatekeeper-system
  chart:
    spec:
      {{- if eq .Values.packages.addons.gatekeeper.sourceType "git" }}
      chart: {{ .Values.packages.addons.gatekeeper.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: gatekeeper
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.gatekeeper.helmRepo.chartName }}
      version: {{ .Values.packages.addons.gatekeeper.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.gatekeeper.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.gatekeeper.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.gatekeeper.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.gatekeeper.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsGatekeeper | nindent 2 }}

  {{- if .Values.packages.addons.gatekeeper.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.gatekeeper.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "overlays"
{{- end }}
