{{- if .Values.packages.addons.vault.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.vault "name" "vault" "defaults" (include "bigbang.defaults.vault" .)) }}
{{- end }}

{{- define "bigbang.defaults.vault" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.packages.addons.monitoring.enabled }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

global:
  imagePullSecrets:
  - name: private-registry

injector:
  {{- if .Values.packages.core.istio.enabled }}
  annotations:
    {{ include "istioAnnotation" . }}
  {{- end }}
  image:
    pullPolicy: {{ .Values.imagePullPolicy }}

server:
  {{- if .Values.packages.core.istio.enabled }}
  annotations:
    {{ include "istioAnnotation" . }}
  {{- end }}
  image:
    pullPolicy: {{ .Values.imagePullPolicy }}
  {{- if and .Values.packages.addons.vault.ingress.cert .Values.packages.addons.vault.ingress.key }}
  {{- if eq .Values.packages.addons.vault.ingress.gateway "passthrough" }}
  volumes:
  - name: tls
    secret:
      secretName: vault-tls
  volumeMounts:
  - name: tls
    mountPath: "/vault/tls"
    readOnly: true
  {{- end }}
  {{- end }}

csi:
  image:
    pullPolicy: {{ .Values.imagePullPolicy }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- $gateway := default "public" .Values.packages.addons.vault.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  nodeCidr: {{ .Values.networkPolicies.nodeCidr }}
  vpcCidr: {{ .Values.networkPolicies.vpcCidr }}  

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.vault.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  vault:
    gateways:
      - istio-system/{{ default "public" .Values.packages.addons.vault.ingress.gateway }}
    {{- if and .Values.packages.addons.vault.ingress.cert .Values.packages.addons.vault.ingress.key }}
    tls:
      cert: {{ .Values.packages.addons.vault.ingress.cert | quote }}
      key:  {{ .Values.packages.addons.vault.ingress.key | quote }}
    {{- end }}

{{- if .Values.packages.core.istio.enabled }}
minio:
  annotations:
    {{ include "istioAnnotation" . }}
{{- end }}        
{{- end -}}
