{{- $pkg := "holocron" }}

{{- /* Create secret */ -}}
{{- if (get .Values.addons $pkg).enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values.addons $pkg) "name" $pkg "defaults" (include (printf "bigbang.defaults.%s" $pkg) .)) }}
{{- end }}

{{- define "bigbang.defaults.holocron" -}}

imagePullSecrets:
- name: private-registry
imagePullPolicy: {{ .Values.imagePullPolicy }}

externalURL: https://holocron.{{ .Values.domain }}

domain: {{ .Values.domain }}

{{- $holocronAuthserviceKey := (dig "selector" "key" "protect" .Values.packages.addons.authservice.values) }}
{{- $holocronAuthServiceValue := (dig "selector" "value" "keycloak" .Values.packages.addons.authservice.values) }}

{{- if .Values.packages.addons.holocron.sso.enabled }}
frontend:
  labels:
    {{ $holocronAuthserviceKey }}: {{ $holocronAuthServiceValue }}
{{- end }}
api:
{{- if .Values.packages.addons.holocron.sso.enabled }}
  labels:
    {{ $holocronAuthserviceKey }}: {{ $holocronAuthServiceValue }}
{{- end }}
  env:
    REQUEST_IP_HEADER: Host
    SSO_ENABLED: {{ .Values.packages.addons.holocron.sso.enabled }}
    SSO_ADMIN_GROUP: {{ .Values.packages.addons.holocron.sso.groups.admin }}
    SSO_LEADERSHIP_GROUP: {{ .Values.packages.addons.holocron.sso.groups.leadership }}
    SSO_GROUPS_KEY: {{ .Values.sso.oidc.claims.groups }}
    SSO_USERNAME_KEY: {{ .Values.sso.oidc.claims.username }}

{{- if .Values.packages.addons.gitlab.enabled }}
{{- $gitlabURL := "http://gitlab-webservice-default.gitlab.svc.cluster.local:8080" }}
collectorGitlabSCM:
  replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-scm
    tag: "3.1.1"
    pullPolicy: IfNotPresent
  instances:
  - accessTokenSecretKey: gitlab-scm-0
    accessToken: {{ .Values.packages.addons.holocron.collectorAuth.gitlabToken }}
    env:
      COLLECTOR_NAME: gitlab-scm-0
      COLLECTOR_INTERVAL_SECONDS: 600
      LOOK_BACK_DAYS: 365
      TARGET_URL: {{ $gitlabURL }}
      COLLECTOR_TARGETS_INTRVL_SECS: 86400
      MAX_REQUESTS_PER_MINUTE: 500
collectorGitlabBuild:
  replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-build
    tag: "3.0.4"
    pullPolicy: IfNotPresent
  instances:
  - accessTokenSecretKey: gitlab-build-0
    accessToken: {{ .Values.packages.addons.holocron.collectorAuth.gitlabToken }}
    env:
      COLLECTOR_NAME: gitlab-build-0
      COLLECTOR_INTERVAL_SECONDS: 600
      LOOK_BACK_DAYS: 365
      TARGET_URL: {{ $gitlabURL }}
      COLLECTOR_TARGETS_INTRVL_SECS: 86400
      MAX_REQUESTS_PER_MINUTE: 500
collectorGitlabWorkflow:
  replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-gitlab-workflow
    tag: "3.0.4"
    pullPolicy: IfNotPresent
  instances:
  - accessTokenSecretKey: gitlab-workflow-0
    accessToken: {{ .Values.packages.addons.holocron.collectorAuth.gitlabToken }}
    env:
      COLLECTOR_NAME: gitlab-workflow-0
      COLLECTOR_INTERVAL_SECONDS: 600
      LOOK_BACK_DAYS: 365
      TARGET_URL: {{ $gitlabURL }}
      COLLECTOR_TARGETS_INTRVL_SECS: 86400
      MAX_REQUESTS_PER_MINUTE: 500
      HIGHEST_PRIORITY_LABELS: priority::1,highest
      HIGH_PRIORITY_LABELS: priority::2,high
      MEDIUM_PRIORITY_LABELS: priority::3,medium
      LOW_PRIORITY_LABELS: priority::4,low
      LOWEST_PRIORITY_LABELS: priority::5,lowest
      DEFAULT_TICKET_PRIORITY: lowest
      FEATURE_LABELS: kind::feature,feature
      DEFECT_LABELS: kind::bug,kind::defect,bug,defect
      MAINTENANCE_LABELS: kind::maintenance,kind::docs,maintenance,docs,documentation
      UNPLANNED_LABELS: kind::unplanned
      DEFAULT_TICKET_TYPE: feature
{{- else }}
collectorGitlabSCM:
  instances: []
collectorGitlabBuild:
  instances: []
collectorGitlabWorkflow:
  instances: []
{{- end }}
{{- if .Values.packages.addons.holocron.jira.enabled }}
collectorJiraWorkflow:
  replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-jira-workflow
    tag: "3.0.4"
    pullPolicy: IfNotPresent
  instances:
  - accessTokenSecretKey: jira-workflow-0
    accessToken: {{ .Values.packages.addons.holocron.collectorAuth.jiraToken }}
    env:
      COLLECTOR_NAME: jira-workflow-0
      COLLECTOR_INTERVAL_SECONDS: 600
      LOOK_BACK_DAYS: 365
      TARGET_URL: {{ .Values.packages.addons.holocron.jira.service }}
      COLLECTOR_TARGETS_INTRVL_SECS: 86400
      MAX_REQUESTS_PER_MINUTE: 500
{{- else }}
collectorJiraWorkflow:
  instances: []
{{- end }}
{{- if .Values.packages.addons.sonarqube.enabled }}
collectorSonarQubeProjectAnalysis:
  replicas: 1
  image:
    repository: registry1.dso.mil/ironbank/holocron/collector-sonarqube-project-analysis
    tag: "3.0.5"
    pullPolicy: IfNotPresent
  instances:
  - accessTokenSecretKey: sonarqube-project-analysis-0
    accessToken: {{ .Values.packages.addons.holocron.collectorAuth.sonarToken }}
    env:
      COLLECTOR_NAME: sonarqube-project-analysis-0
      COLLECTOR_INTERVAL_SECONDS: 600
      LOOK_BACK_DAYS: 365
      TARGET_URL: "http://sonarqube-sonarqube.gitlab.svc.cluster.local:9000"
      COLLECTOR_TARGETS_INTRVL_SECS: 86400
      MAX_REQUESTS_PER_MINUTE: 500
{{- else }}
collectorSonarQubeProjectAnalysis:
  instances: []
{{- end }}

postgresql:
  {{- if .Values.packages.addons.holocron.database.host }}
  enabled: false
  service:
    name: {{ .Values.packages.addons.holocron.database.host }}
    ports:
      postgresql: {{ .Values.packages.addons.holocron.database.port }}
  {{- else }}
  enabled: true
  service:
    ports:
      postgresql: {{ .Values.packages.addons.holocron.database.port }}
  {{- end }}
    
  auth:
    secretKey: password
    username: {{ .Values.packages.addons.holocron.database.username }}
    password: {{ .Values.packages.addons.holocron.database.password }}
    database: {{ .Values.packages.addons.holocron.database.database }}
  tls:
    enabled: true
    autoGenerated: true

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.holocron.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  injection: enabled
  holocron:
    gateways:
    - istio-system/{{ default "public" .Values.packages.addons.holocron.ingress.gateway }}
    hosts:
    - holocron.{{ .Values.domain }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  egressHostLabels:
    {{- if .Values.packages.addons.gitlab.enabled }}
    app.kubernetes.io/name: gitlab
    {{- end }}
    {{- if .Values.packages.addons.holocron.jira.enabled }}
    {{ toYaml .Values.packages.addons.holocron.jira.service.label | nindent 4 }}
    {{- end }}
    {{- if .Values.packages.addons.sonarqube.enabled }}
    app: sonarqube
    {{- end }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

{{- end }}
