{{- if and (((.Values.addons).backstage).enabled) ((.Values.kyverno).enabled) }}
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
annotations:
labels:
    app: backstage
name: backstage-disallow-auto-mount-service-account-token-exception
namespace: {{ .Release.Namespace }}
spec:
exceptions:
- policyName: disallow-auto-mount-service-account-token
    ruleNames:
    - disallow-auto-mount-service-account-token
match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        - ServiceAccount
        names:
        - backstage
        - backstage*
        namespaces:
        - backstage
{{- end }}