{{- define "bigbang.policyexceptions.fluentbit" }}
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-add-default-securitycontext-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: add-default-securitycontext
      ruleNames:
      - add-default-securitycontext
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-disallow-privileged-containers-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: disallow-privileged-containers
      ruleNames:
      - disallow-privileged-containers
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-disallow-tolerations-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: disallow-tolerations
      ruleNames:
      - disallow-tolerations
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-require-non-root-group-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-non-root-group
      ruleNames:
      - require-non-root-group
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-require-non-root-user-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-non-root-user
      ruleNames:
      - require-non-root-user
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-restrict-host-path-mount-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-host-path-mount
      ruleNames:
      - restrict-host-path-mount
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-restrict-selinux-type-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-selinux-type
      ruleNames:
      - restrict-selinux-type
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: fluentbit
    name: fluentbit-restrict-volume-types-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-volume-types
      ruleNames:
      - restrict-volume-types
    match:
      any:
      - resources:
          names:
          - fluentbit-fluent-bit*
          namespaces:
          - fluentbit
{{- end }}