{{- if and ((.Values.monitoring).enabled) (.Values.kyverno).enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  labels:
    app: monitoring
  name: monitoring-disallow-auto-mount-service-account-token-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-auto-mount-service-account-token
    ruleNames:
    - disallow-auto-mount-service-account-token
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        names:
        - notification-controller*
        - helm-controller*
        - source-controller*
        - kustomize-controller*
        namespaces:
        - flux-system
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  labels:
    app: monitoring
  name: monitoring-disallow-tolerations-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-tolerations
    ruleNames:
    - disallow-tolerations
  match:
    any:
    - resources:
        names:
        - monitoring-monitoring-prometheus-node-exporter*
        namespaces:
        - monitoring
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  labels:
    app: monitoring
  name: monitoring-restrict-host-path-mount-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: restrict-host-path-mount
    ruleNames:
    - restrict-host-path-mount
  match:
    any:
    - resources:
        names:
        - monitoring-monitoring-prometheus-node-exporter*
        namespaces:
        - monitoring
---
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  labels:
    app: monitoring
  name: monitoring-restrict-volume-types-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: restrict-volume-types
    ruleNames:
    - restrict-volume-types
  match:
    any:
    - resources:
        names:
        - monitoring-monitoring-prometheus-node-exporter*
        namespaces:
        - monitoring
{{- end }}