{{- if and ((.Values.twistlock).enabled) (.Values.kyverno).enabled }}
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-add-default-capability-drop-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: add-default-capability-drop
      ruleNames:
      - add-default-capability-drop
    match:
      any:
      - resources:
          names:
          - twistlock-console*
          - twistlock-defender-ds*
          - volume-upgrade*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-add-default-securitycontext-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: add-default-securitycontext
      ruleNames:
      - add-default-securitycontext
    match:
      any:
      - resources:
          names:
          - twistlock-console*
          - twistlock-defender-ds*
          - volume-upgrade-job*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-disallow-host-namespaces-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: disallow-host-namespaces
      ruleNames:
      - disallow-host-namespaces
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-disallow-tolerations-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: disallow-tolerations
      ruleNames:
      - disallow-tolerations
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-require-drop-all-capabilities-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-drop-all-capabilities
      ruleNames:
      - require-drop-all-capabilities
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          - volume-upgrade*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-require-non-root-group-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-non-root-group
      ruleNames:
      - require-non-root-group
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          - volume-upgrade-job*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-require-non-root-user-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: require-non-root-user
      ruleNames:
      - require-non-root-user
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          - volume-upgrade-job*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-apparmor-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-apparmor
      ruleNames:
      - restrict-apparmor
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-capabilities-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-capabilities
      ruleNames:
      - restrict-capabilities
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-host-path-mount-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-host-path-mount
      ruleNames:
      - restrict-host-path-mount
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-host-path-write-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-host-path-write
      ruleNames:
      - restrict-host-path-write
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-selinux-type-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-selinux-type
      ruleNames:
      - restrict-selinux-type
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
---
  apiVersion: kyverno.io/v2
  kind: PolicyException
  metadata:
    annotations:
    labels:
      app: twistlock
    name: twistlock-restrict-volume-types-exception
    namespace: {{ .Release.Namespace }}
  spec:
    exceptions:
    - policyName: restrict-volume-types
      ruleNames:
      - restrict-volume-types
    match:
      any:
      - resources:
          names:
          - twistlock-defender-ds*
          namespaces:
          - twistlock
{{- end }}