{{- if and (eq .Values.kyverno.sourceType "git") (not .Values.offline) (or .Values.kyverno.enabled .Values.kyvernoPolicies.enabled .Values.kyvernoReporter.enabled) }}
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyvernocrds
  namespace: {{ .Release.Namespace }}
spec:
  interval: 1m
  targetNamespace: {{ .Release.Namespace }}
  sourceRef:
    kind: GitRepository
    name: kyverno
  path: "./chart/crds"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyvernoparent
  namespace: {{ .Release.Namespace }}
spec:
  interval: 1m
  dependsOn:
    - name: kyvernocrds
      namespace: {{ .Release.Namespace }}
  path: ./chart
  prune: false
  sourceRef:
    kind: GitRepository
    name: kyverno
    namespace: {{ .Release.Namespace }}
  targetNamespace: {{ .Release.Namespace }}
{{- end }}