{{- if and (or (and .Values.packages.addons.grafana.enabled .Values.packages.addons.grafana.sso.enabled) (and .Values.packages.addons.monitoring.sso.enabled (dig "grafana" "client_id" false .Values.packages.addons.monitoring.sso))) (or .Values.sso.certificate_authority (dig "certificateAuthority" "cert" false .Values.sso)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (dig "certificateAuthority" "secretName" "" .Values.sso) .Values.sso.secretName }}-grafana
  namespace: monitoring
type: Opaque
data:
  ca.pem: {{ default (dig "certificateAuthority" "cert" "" .Values.sso) .Values.sso.certificate_authority | b64enc }}
{{- end }}

