{{- $fluxSettingsIstioOperator := merge .Values.packages.core.istioOperator.flux .Values.flux -}}
{{- if .Values.packages.core.istioOperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/istio-operator/values.yaml") . | sha256sum }}
spec:
  targetNamespace: istio-operator
  chart:
    spec:
      {{- if eq .Values.packages.core.istioOperator.sourceType "git" }}
      chart: {{ .Values.packages.core.istioOperator.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: istio-operator
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.core.istioOperator.helmRepo.chartName }}
      version: {{ .Values.packages.core.istioOperator.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.core.istioOperator.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.core.istioOperator.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.core.istioOperator.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.core.istioOperator.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsIstioOperator | nindent 2 }}

  {{- if .Values.packages.core.istioOperator.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.core.istioOperator.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.packages.addons.gatekeeper.enabled .Values.packages.core.kyvernoPolicies.enabled }}
  dependsOn:
    {{- if .Values.packages.addons.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.core.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
