{{- if .Values.packages.core.istioOperator.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.core.istioOperator "name" "istio-operator" "defaults" (include "bigbang.defaults.istioOperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.istioOperator" -}}
createNamespace: false

enterprise: {{ .Values.packages.core.istio.enterprise }}
imagePullPolicy: {{ .Values.imagePullPolicy }}

imagePullSecrets:
  - private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}
{{- end -}}
