{{- if .Values.packages.addons.neuvector.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
  labels:
    app.kubernetes.io/name: neuvector
    app.kubernetes.io/component: "sandbox"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and (include "istioEnabled" .) (eq (dig "istio" "injection" "enabled" .Values.packages.addons.neuvector) "enabled")) }}
{{- end }}