{{- define "defaultGatewayClassName" -}}
gatewayClassName: istio
{{- end -}}

{{- range $name, $gw := $.Values.gateways }}
{{- if $gw.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $name }}
  namespace: {{ $gw.namespace | default "istio-gateway" }}
  labels:
{{ toYaml $gw.labels | indent 4 }}
  annotations:
{{ toYaml $gw.annotations | indent 4 }}
spec:
{{- $baseSpec := $gw.spec | default dict }}
{{- if $gw.templatedSpec }}
{{- $templatedSpecYaml := tpl (toYaml $gw.templatedSpec) $ }}
{{- $processedTemplatedSpec := fromYaml $templatedSpecYaml }}
{{ toYaml (merge (fromYaml (include "defaultGatewayClassName" .)) $baseSpec $processedTemplatedSpec) | indent 2 }}
{{- else }}
{{ toYaml (merge (fromYaml (include "defaultGatewayClassName" .)) $baseSpec) | indent 2 }}
{{- end }}
status: {}
{{ end -}}
{{ end -}}
