{{- range $name, $gw := $.Values.gateways }}
{{- if and $gw.enabled $gw.httpToHttpsRedirect }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "{{ $name }}-http-to-https"
  namespace: {{ $gw.namespace | default "istio-gateway" }}
  labels:
{{ toYaml $gw.labels | indent 4 }}
  annotations:
{{ toYaml $gw.annotations | indent 4 }}
spec:
  parentRefs:
  - name: {{ $name }}
    sectionName: http
  hostnames:
  - '*'
  rules:
  
status: {}
{{ end -}}
{{ end -}}
