{{- if .Values.tempo.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: tempo-waypoint
{{- end }}
