{{- $nexusOldValues := default dict .Values.packages.addons.nexus -}}
{{- $nexusValues := mergeOverwrite $nexusOldValues .Values.packages.addons.nexusRepositoryManager -}}
{{- $gitCredsSecretDict := dict
  "name" "nexusRepositoryManager"
  "targetScope" $nexusValues
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
