{{- $nexusOldValues := default dict .Values.packages.addons.nexus -}}
{{- $nexusValues := mergeOverwrite $nexusOldValues .Values.packages.addons.nexusRepositoryManager -}}
{{- if and $nexusValues.enabled $nexusValues.sso.enabled (or .Values.sso.certificate_authority (dig "certificateAuthority" "cert" false .Values.sso)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{default (dig "certificateAuthority" "secretName" "" .Values.sso) .Values.sso.secretName}}
  namespace: nexus-repository-manager
type: Opaque
data:
  ca.pem: {{ default (dig "certificateAuthority" "cert" "" .Values.sso) .Values.sso.certificate_authority | b64enc }}
{{- end }}
