{{- if and .Values.loki.enabled (not .Values.elasticsearchKibana.enabled) }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and (or .Values.istio.enabled .Values.istioGateway.enabled) (eq (dig "istio" "injection" "enabled" .Values.loki) "enabled")) }}
{{- end }}
