{{- if and .Values.loki.enabled (not .Values.elasticsearchKibana.enabled) }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $istioInjection := and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.loki) "enabled") }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if and $istioEnabled .Values.ztunnel.enabled }}
    istio.io/dataplane-mode: ambient
    {{- else if $istioInjection }}
    istio-injection: enabled
    {{- end }}
{{- end }}
