{{- if and .Values.loki.enabled (not .Values.elasticsearchKibana.enabled) }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: logging-waypoint
{{- end }}
