{{- $pkg := "istioGatewayPublic" }}

{{- /* Create secret */ -}}
{{- if (get .Values $pkg).enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values $pkg) "name" ($pkg | kebabcase) "defaults" (include (printf "bigbang.defaults.%s" $pkg | kebabcase) .)) }}
{{- end }}

{{- define "bigbang.defaults.istio-gateway-public" -}}
createNamespace: true

imagePullPolicy: {{ .Values.imagePullPolicy }}

imagePullSecrets:
  - name: private-registry-public

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

gateway:
  domain: {{ .Values.domain }}

labels:
  istio: ingressgateway

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
{{- end -}}

