{{- $pkg := "kyvernoReporter" }}
{{- if (get .Values $pkg).enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: {{ $pkg | kebabcase }}
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and (or .Values.istio.enabled .Values.istio3.enabled) (eq (dig "istio" "injection" "enabled" (get .Values $pkg)) "enabled")) }}
  name: kyverno-reporter
{{- end }}
