{{- $pkg := "kyvernoReporter" }}
{{- if (get .Values $pkg).enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $istioInjection := and $istioEnabled (eq (dig "istio" "injection" "enabled" .Values.kyvernoReporter) "enabled") }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: {{ $pkg | kebabcase }}
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    {{- if and $istioEnabled .Values.ztunnel.enabled }}
    istio.io/dataplane-mode: ambient
    {{- else if $istioInjection }}
    istio-injection: enabled
    {{- end }}
  name: kyverno-reporter
{{- end }}