{{- $pkg := "kyvernoReporter" }}
{{- if (get .Values $pkg).enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: {{ $pkg | kebabcase }}
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: kyverno-reporter-waypoint
  name: kyverno-reporter
{{- end }}