{{- range $values := .Values.istioGateway.gateways }}
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: testing
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    {{- $values.selector | default (dict) | toYaml | nindent 4 }}
  servers:
{{- if (dig "autoHttpRedirect" "enabled" true $values) }}    
  - hosts:
{{- range $servers := $values.servers }}
{{- range $host := $servers.hosts }}
{{- if eq $servers.port.protocol "HTTPS" }}
    - '{{- tpl $host $ }}'
{{- end }}
{{- end }}
{{- end }}
    port:
      name: http
      number: 8080
      protocol: HTTP
    tls:
      httpsRedirect: true
{{- end }}
    {{- tpl (toYaml $values.servers) $ | nindent 2 }}
{{- end }}
