{{- if .Values.istio3.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  labels:
    istio-gateway-managed: Reconcile
    istio-injection: enabled
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
