{{- define "bigbang.istio-gateway-secrets" -}}
{{- $root := . -}}
{{- $enabledGateways := include "enabledGateways" $ | fromYaml }}
{{- $enabledGateways = include "bigbang.istio-gateway.generate-ingress-netpols" (list $ $enabledGateways) | fromYaml }}
{{- range $name, $gw := $enabledGateways }}
---
{{- if and (typeIs "map[string]interface {}" $gw) (hasKey $gw "overlays") }}
  {{ $_ := unset $gw.overlays "gatewayCerts" }}
{{- end }}
{{ include "values-secret" (dict 
  "root" $root 
  "name" (printf "istio-%s-gateway" $name)
  "defaults" ($gw.defaults | toYaml)
  "package" (dict "values" $gw.overlays "disableAutomaticPassthroughValues" true)
) }}
{{- end }}
{{- end }}

{{- if and .Values.istiod.enabled .Values.istioGateway.enabled }}
{{- include "bigbang.istio-gateway-secrets" . }}
{{- end }}
