{{- if and .Values.packages.addons.loki.enabled (not .Values.packages.addons.elasticsearchKibana.enabled) }}
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    app.kubernetes.io/name: logging
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and (include "istioEnabled" .) (eq (dig "istio" "injection" "enabled" .Values.packages.addons.loki) "enabled")) }}
{{- end }}
