{{- if include "alloy.shouldDeployUpgradeResources" . }}
  {{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alloy-api-egress-upgrade-job
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  egress:
  - to:
    - ipBlock:
        cidr: "0.0.0.0/0"
        # ONLY Block requests to AWS metadata IP
        except:
        - 169.254.169.254/32
  podSelector:
    matchLabels:
      app.kubernetes.io/name: bigbang-alloy-upgrade-job
  policyTypes:
  - Egress
  {{- end }}
{{- end }}