{{- if include "alloy.shouldDeployUpgradeResources" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: bb-alloy-upgrade
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 480
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bigbang-alloy-upgrade-job
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: alloy-bb-upgrade
      automountServiceAccountToken: true
      containers:
        - name: bb-alloy-upgrade
          image: "{{ $.Values.addons.alloy.autoRollingUpgrade.image.repository }}:{{ $.Values.addons.alloy.autoRollingUpgrade.image.tag }}"
          command:
            - "/bin/bash"
            - "-c"
            - |
              # Delete the alloy helmrelease with target namespace in monitoring prior to ugpragde and check if successful
              if kubectl delete helmrelese alloy -n {{ .Release.Namespace }}; then
                echo "helmrelease alloy (in monitoring namespace) deleted successfully."
              else
                echo "[ERROR] Failed to delete alloy helm release (in monitoring namespace)." >&2
                exit 1
              fi

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
      restartPolicy: Never
{{- end }}
