{{- if include "alloy.shouldDeployUpgradeResources" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alloy-bb-upgrade
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bb-alloy-upgrade-view
subjects:
- kind: ServiceAccount
  name: alloy-bb-upgrade
  namespace: monitoring
{{- end }}