{{- if include "alloy.shouldDeployUpgradeResources" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bb-alloy-upgrade-view
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
    
rules:
- apiGroups: ["security.istio.io", "networking.k8s.io", "apps", "","discovery.k8s.io"]
  resources: ["endpoints",authorizationpolicies", "networkpolicies", "deployments", "statefulsets", "daemonsets", "services", "pods", "serviceaccount","peerauthentications"]
  verbs: ["get", "list", "delete"]
{{- end }}