{{- if include "alloy.shouldDeployUpgradeResources" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bb-alloy-upgrade-view
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["list","delete","get"]
{{- end }}