{{- if include "alloy.shouldDeployUpgradeResources" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-bb-upgrade
  namespace: monitoring
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
{{- end }}