{{- if and .Values.ztunnel.enabled .Values.kyvernoPolicies.enabled }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: ztunnel-exceptions
  namespace: kyverno
  labels:
    app.kubernetes.io/name: ztunnel
    {{- include "commonLabels" . | nindent 4 }}
spec:
  exceptions:
    - policyName: disallow-privilege-escalation
      ruleNames:
        - disallow-privilege-escalation
    - policyName: require-non-root-user
      ruleNames:
        - non-root-user
    - policyName: restrict-capabilities
      ruleNames:
        - capabilities
    - policyName: restrict-host-path-mount
      ruleNames:
        - restrict-hostpath-dirs
    - policyName: restrict-host-path-write
      ruleNames:
        - require-readonly-hostpath
    - policyName: restrict-volume-types
      ruleNames:
        - restrict-volume-types
  match:
    any:
      - resources:
          kinds:
            - Pod
          namespaces:
            - istio-system
          names:
            - "ztunnel-*"
{{- end }}
