{{- $fluxSettingsAnchore := merge .Values.packages.addons.anchore.flux .Values.flux -}}
{{- if .Values.packages.addons.anchore.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anchore
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/anchore/values.yaml") . | sha256sum }}
spec:
  releaseName: anchore
  targetNamespace: anchore
  chart:
    spec:
      {{- if eq .Values.packages.addons.anchore.sourceType "git" }}
      chart: {{ .Values.packages.addons.anchore.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: anchore
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.anchore.helmRepo.chartName }}
      version: {{ .Values.packages.addons.anchore.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.anchore.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.anchore.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.anchore.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.anchore.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsAnchore | nindent 2 }}

  {{- if .Values.packages.addons.anchore.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.anchore.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-anchore-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.packages.core.istio.enabled .Values.packages.addons.monitoring.enabled }}
  dependsOn:
    {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
