{{- if .Values.packages.addons.anchore.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.anchore "name" "anchore" "defaults" (include "bigbang.defaults.anchore" .)) }}
{{- end }}

{{- define "bigbang.defaults.anchore" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ include "istioEnabled" . }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.anchore.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  injection: {{ ternary "enabled" "disabled" (and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.anchore) "enabled")) }}
  ui:
    gateways:
      - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.packages.addons.anchore.ingress.gateway }}
  api:
    gateways:
      - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.packages.addons.anchore.ingress.gateway }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}
  {{- if and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.anchore) "enabled") }}
  {{- if (eq (dig "values" "istio" "mtls" "mode" "STRICT" .Values.packages.addons.anchore) "STRICT") }}
  serviceMonitor:
    scheme: "https"
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true
  {{- end }}
  {{- end }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  istioNamespaceSelector:
  {{ include "istioNamespaceSelector" . | nindent 4 }}
  ingressLabels:
    {{- $gateway := default "public" .Values.packages.addons.anchore.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}

{{- if .Values.packages.addons.anchore.enterprise.licenseYaml }}
enterpriseLicenseYaml: |
  {{ .Values.packages.addons.anchore.enterprise.licenseYaml | nindent 2 }}
{{- end }}

sso:
  enabled: {{ .Values.packages.addons.anchore.sso.enabled }}
  spEntityId: {{ .Values.packages.addons.anchore.sso.client_id }}
  {{- $anchoreUrl := first (dig "istio" "ui" "hosts" list .Values.packages.addons.anchore.values) }}
  acsUrl: https://{{ tpl ($anchoreUrl | default (printf "%s.%s" "anchore" $domainName)) . }}/service/sso/auth/keycloak
  idpMetadataUrl: "{{ include "sso.saml.descriptor" . }}"
  roleAttribute: {{ .Values.packages.addons.anchore.sso.role_attribute }}

global:
  imagePullSecretName: private-registry

imagePullPolicy: {{ .Values.imagePullPolicy }}

postgresql:
  {{- if .Values.packages.core.istio.enabled }}
  podAnnotations:
    {{ include "istioAnnotation" . }}
  {{- end}}
  imagePullSecrets: private-registry
  {{- if and .Values.packages.addons.anchore.database.host .Values.packages.addons.anchore.database.port .Values.packages.addons.anchore.database.username .Values.packages.addons.anchore.database.password .Values.packages.addons.anchore.database.database }}
  enabled: false
  postgresUser: {{ .Values.packages.addons.anchore.database.username }}
  postgresPassword: {{ .Values.packages.addons.anchore.database.password }}
  postgresDatabase: {{ .Values.packages.addons.anchore.database.database }}
  externalEndpoint: "{{ .Values.packages.addons.anchore.database.host }}"
  postgresPort: {{ .Values.packages.addons.anchore.database.port }}
  {{- end }}
{{- if .Values.packages.addons.anchore.adminPassword }}
anchoreConfig:
  default_admin_password: {{ .Values.packages.addons.anchore.adminPassword }}
{{- end }}

feeds:
  istio:
    enabled: {{ .Values.packages.core.istio.enabled }}
    injection: {{ ternary "enabled" "disabled" (and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.anchore) "enabled")) }}

  feeds-db:
    {{- if .Values.packages.core.istio.enabled }}
    podAnnotations:
      {{ include "istioAnnotation" . }}
    {{- end }}
    imagePullSecrets: private-registry
    {{- if and .Values.packages.addons.anchore.database.host .Values.packages.addons.anchore.database.port .Values.packages.addons.anchore.database.username .Values.packages.addons.anchore.database.password .Values.packages.addons.anchore.database.feeds_database }}
    enabled: false
    postgresUser: {{ .Values.packages.addons.anchore.database.username }}
    postgresPassword: {{ .Values.packages.addons.anchore.database.password }}
    postgresDatabase: {{ .Values.packages.addons.anchore.database.feeds_database }}
    externalEndpoint: "{{ .Values.packages.addons.anchore.database.host }}"
    postgresPort: {{ .Values.packages.addons.anchore.database.port }}
    {{- end }}

ui:
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  imagePullSecretName: private-registry

ui-redis:
  {{- if and .Values.packages.addons.anchore.redis.host .Values.packages.addons.anchore.redis.port .Values.packages.addons.anchore.redis.password }}
  enabled: false
  externalEndpoint: "redis://{{ .Values.packages.addons.anchore.redis.username | default "nouser" }}:{{ .Values.packages.addons.anchore.redis.password }}@{{ .Values.packages.addons.anchore.redis.host }}:{{ .Values.packages.addons.anchore.redis.port }}"
  auth:
    password: {{ .Values.packages.addons.anchore.redis.password }}
  {{- end }}
  {{- if .Values.packages.core.istio.enabled }}
  master:
    podAnnotations:
      {{ include "istioAnnotation" . }}
  replica:
    podAnnotations:
      {{ include "istioAnnotation" . }}
  {{- end }}
  image:
    pullSecrets:
      - private-registry
  {{- if and .Values.packages.addons.monitoring.enabled (not (and .Values.packages.addons.anchore.redis.host .Values.packages.addons.anchore.redis.port .Values.packages.addons.anchore.redis.password)) }}
  metrics:
    enabled: true
    image:
      pullSecrets:
        - private-registry
    serviceMonitor:
      enabled: true
      namespace: anchore
      selector:
        app.kubernetes.io/name: anchore-ui-redis
        app.kubernetes.io/instance: anchore
      {{- if and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.anchore) "enabled") }}
      {{- if (eq (dig "values" "istio" "mtls" "mode" "STRICT" .Values.packages.addons.anchore) "STRICT") }}
      scheme: "https"
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true
      {{- end }}
      {{- end }}
    prometheusRule:
      enabled: true
      namespace: monitoring
  {{- end }}

{{- end }}
