{{- if and .Values.istio3.enabled .Values.istioGatewayPassthrough.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: passthrough
  namespace: istio-gateway
  labels:
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
spec:
  selector:
    app: istio-gateway-passthrough-ingressgateway
  servers:
    - hosts:
        - 'keycloak.dev.bigbang.mil'
      port:
        name: http
        number: 8080
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - 'keycloak.dev.bigbang.mil'
      port:
        name: https
        number: 8443
        protocol: HTTPS
      tls:
        credentialName: private-cert
        mode: SIMPLE
{{- end }}
