{{- $fluxSettingsHaProxy := merge .Values.packages.addons.proxy.flux .Values.flux -}}
{{- $monitoringInjection := dig "istio" "injection" "enabled" .Values.packages.addons.monitoring }}
{{- if and .Values.packages.core.istio.enabled .Values.packages.addons.monitoring.enabled .Values.packages.addons.monitoring.sso.enabled (eq $monitoringInjection "disabled") }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-sso
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/component: "developer-tools"
  {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/haproxy/values.yaml") . | sha256sum }}
spec:
  targetNamespace: authservice
  chart:
    spec:
      {{- if eq .Values.packages.addons.proxy.sourceType "git" }}
      chart: {{ .Values.packages.addons.proxy.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: haproxy
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.proxy.helmRepo.chartName }}
      version: {{ .Values.packages.addons.proxy.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.proxy.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.proxy.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.proxy.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.proxy.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m
  {{- if .Values.packages.addons.proxy.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.proxy.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-haproxy-sso-values
      kind: Secret
      valuesKey: "overlays"

  {{- toYaml $fluxSettingsHaProxy | nindent 2 }}

  dependsOn:
    {{- if .Values.packages.core.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.packages.addons.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}

{{- end }}
