{{- if and .Values.packages.addons.kiali.enabled .Values.packages.addons.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: kiali
  labels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
stringData:
{{- if (dig "admin" "existingSecret" "" .Values.packages.addons.grafana.values) }}
  {{- $passwordKey := (dig "admin" "passwordKey" "admin-password" .Values.packages.addons.grafana.values) }}
  {{- with lookup "v1" "Secret" "monitoring" .Values.packages.addons.grafana.values.admin.existingSecret }}
  password: {{ (get .data $passwordKey | b64dec) | default "prom-operator" }}
  {{- end }}
{{- else }}
  password: {{ dig "adminPassword" "prom-operator" .Values.packages.addons.grafana.values }}
{{- end }}
{{- end }}
