{{- if and .Values.packages.addons.kiali.enabled .Values.packages.addons.kiali.sso.client_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: kiali
type: kubernetes.io/opaque
stringData:
  oidc-secret: {{ .Values.packages.addons.kiali.sso.client_secret }}
{{- end }}
