{{- if .Values.packages.addons.kiali.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.kiali "name" "kiali" "defaults" (include "bigbang.defaults.kiali" .)) }}
{{- end }}

{{- define "bigbang.defaults.kiali" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
domain: {{ $domainName }}

sso:
  enabled: {{ .Values.packages.addons.kiali.sso.enabled }}

openshift: {{ .Values.openshift}}

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

istio:
  enabled: {{ include "istioEnabled" . }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.kiali.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
    monitoring:
      enabled: {{ .Values.packages.addons.monitoring.enabled }}
  kiali:
    gateways:
    - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.packages.addons.kiali.ingress.gateway }}

{{- if include "istioEnabled" . }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

{{- if and .Values.packages.addons.kiali.enabled .Values.packages.addons.kiali.sso.enabled (or .Values.sso.certificate_authority (dig "certificateAuthority" "cert" false .Values.sso))  }}
oidcCaCert: {{ default (dig "certificateAuthority" "cert" "" .Values.sso) .Values.sso.certificate_authority | quote }}
{{- end }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}
elasticsearch:
  enabled: {{ .Values.packages.addons.elasticsearchKibana.enabled }}
cr:
  spec:
    {{- if .Values.packages.core.istioCore.enabled }}
    istio_namespace: istio-system
    {{- end}}
    deployment:
      image_pull_policy: {{ .Values.imagePullPolicy }}
      {{- if include "istioEnabled" . }}
      pod_annotations:
        {{ include "istioAnnotation" . }}
      {{- end }}
      hpa:
        spec:
          maxReplicas: 2
          minReplicas: 1
          targetCPUUtilizationPercentage: 80
    server:
      web_port: "443"
    auth:
      {{- if .Values.packages.addons.kiali.sso.enabled }}
      strategy: openid
      openid:
        client_id: "{{ .Values.packages.addons.kiali.sso.client_id }}"
        disable_rbac: true
        issuer_uri: "{{ include "sso.url" . }}"
        scopes:
        - openid
        - email
        username_claim: {{ dig "oidc" "claims" "email" "email" .Values.sso }}
      {{- else }}
      strategy: token
      {{- end }}
    external_services:
      grafana:
        enabled: {{ .Values.packages.addons.grafana.enabled }}
        {{- $grafanaUrl := first (dig "istio" "grafana" "hosts" list .Values.packages.addons.grafana.values) }}
        url: https://{{ tpl ($grafanaUrl | default (printf "%s.%s" "grafana" $domainName)) . }}
        {{- if .Values.packages.addons.grafana.enabled }}
        auth:
          {{- if (dig "admin" "existingSecret" "" .Values.packages.addons.grafana.values) }}
          {{- $userKey := (dig "admin" "userKey" "admin-user" .Values.packages.addons.grafana.values) }}
          {{- with lookup "v1" "Secret" "monitoring" .Values.packages.addons.grafana.values.admin.existingSecret }}
          username: {{ (get .data $userKey | b64dec) | default "admin" }}
          {{- end }}
          {{- else }}
          username: {{ dig "adminUser" "admin" .Values.packages.addons.grafana.values }}
          {{- end }}
          password: "secret:grafana-auth:password"
        {{- end }}
      tracing:
        enabled: {{ .Values.packages.addons.jaeger.enabled }}
        {{- $tracingUrl := first (dig "istio" "jaeger" "hosts" list .Values.packages.addons.jaeger.values) }}
        url: https://{{ tpl ($tracingUrl | default (printf "%s.%s" "tracing" $domainName )) . }}
      istio:
        component_status:
          components:
            - app_label: istiod
              is_core: true
              is_proxy: false
            {{- if .Values.packages.core.istio.enabled }}
            {{- range $name, $values := .Values.packages.core.istio.ingressGateways }}
            {{ if ne $values.enabled false }}
            - app_label: {{ $name }}
              is_core: true
              is_proxy: true
            {{- end }}
            {{- end }}
            {{- range $name, $values := .Values.packages.core.istio.values.ingressGateways }}
            {{ if ne $values.enabled false }}
            - app_label: {{ $name }}
              is_core: true
              is_proxy: true
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.packages.core.istioGateway.enabled }}
            {{- range $name, $gw := include "enabledGateways" $ | fromYaml }}
            {{- if eq $gw.type "ingressgateway" }}
            - app_label: {{ $gw.serviceName }}
              is_core: true
              is_proxy: true
              namespace: istio-gateway
            {{- end -}}
            {{- end -}}
            {{- end -}}
        {{- if .Values.packages.core.istioCore.enabled }}
        ingress_gateway_namespace: istio-gateway
        egress_gateway_namespace: istio-gateway
        {{- end }}
    api:
      namespaces:
        # bigbang watches all!
        exclude: []
networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  istioNamespaceSelector:
  {{ include "istioNamespaceSelector" . | nindent 4 }}
  ingressLabels:
    {{- if .Values.packages.core.istio.enabled }}
    {{- $gateway := default "public" .Values.packages.addons.kiali.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}
    {{- end }}
    {{- if .Values.packages.core.istioCore.enabled }}
    app: public-ingressgateway
    istio: ingressgateway
    {{- end }}
{{- end -}}
