#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
METADATA_PATH="${REPO_ROOT}/chart/package-metadata.yaml"
SCHEMA_PATH="${REPO_ROOT}/chart/values.schema.json"
VALUES_PATH="${REPO_ROOT}/chart/values.yaml"
MIGRATION_PATH="${REPO_ROOT}/scripts/migrate-values-3-to-4.sh"
JQ_PROGRAM="${REPO_ROOT}/scripts/generate-package-schemas.jq"
MODE=${1:---write}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

if [[ $# -gt 1 || "$MODE" != "--write" && "$MODE" != "--check" ]]; then
  fail "usage: $(basename "$0") [--write|--check]"
fi

command -v jq >/dev/null 2>&1 || fail "jq is required"
command -v yq >/dev/null 2>&1 || fail "Mike Farah yq v4 is required"
[[ "$(yq --version 2>/dev/null)" =~ version\ v4\. ]] || fail "Mike Farah yq v4 is required"

TASK_TMP=$(mktemp -d "${TMPDIR:-/tmp}/bigbang-package-schemas.XXXXXX")
cleanup() {
  rm -f "${TASK_TMP}/metadata.json" "${TASK_TMP}/values.json" \
    "${TASK_TMP}/values.schema.json" "${TASK_TMP}/migrate-values-3-to-4.sh"
  rmdir "$TASK_TMP"
}
trap cleanup EXIT

yq -o=json '.' "$METADATA_PATH" >"${TASK_TMP}/metadata.json"
yq -o=json '.' "$VALUES_PATH" >"${TASK_TMP}/values.json"

while IFS= read -r template_directory; do
  [[ -d "${REPO_ROOT}/chart/templates/${template_directory}" ]] \
    || fail "template directory chart/templates/${template_directory} does not exist"
done < <(yq -r '.packages[].templateDirectory' "$METADATA_PATH")

jq --slurpfile metadata "${TASK_TMP}/metadata.json" \
  --slurpfile values "${TASK_TMP}/values.json" \
  -f "$JQ_PROGRAM" "$SCHEMA_PATH" >"${TASK_TMP}/values.schema.json"

{
  sed -n '1,/^# BEGIN GENERATED PACKAGE METADATA$/p' "$MIGRATION_PATH" | sed '$d'
  printf '%s\n' '# BEGIN GENERATED PACKAGE METADATA'
  printf '%s\n' '# Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml.'
  printf '%s\n' 'ROOT_PACKAGES=('
  yq -r '.packages | to_entries[] | select(.value.category == "core") | "  " + .key' "$METADATA_PATH"
  printf '%s\n\n' ')'
  printf '%s\n' 'ADDON_PACKAGES=('
  yq -r '.packages | to_entries[] | select(.value.category == "addon") | "  " + .key' "$METADATA_PATH"
  printf '%s\n' ')'
  printf '%s\n' '# END GENERATED PACKAGE METADATA'
  sed -n '/^# END GENERATED PACKAGE METADATA$/,$p' "$MIGRATION_PATH" | sed '1d'
} >"${TASK_TMP}/migrate-values-3-to-4.sh"

if [[ "$MODE" == "--check" ]]; then
  STALE_FILES=()
  cmp -s "$SCHEMA_PATH" "${TASK_TMP}/values.schema.json" || STALE_FILES+=("$SCHEMA_PATH")
  cmp -s "$MIGRATION_PATH" "${TASK_TMP}/migrate-values-3-to-4.sh" || STALE_FILES+=("$MIGRATION_PATH")
  if [[ ${#STALE_FILES[@]} -gt 0 ]]; then
    fail "generated files are stale: ${STALE_FILES[*]}; run scripts/generate-package-schemas.sh --write"
  fi
  printf '%s\n' 'Generated package metadata files are up to date.'
else
  cp "${TASK_TMP}/values.schema.json" "$SCHEMA_PATH"
  cp "${TASK_TMP}/migrate-values-3-to-4.sh" "$MIGRATION_PATH"
  chmod +x "$MIGRATION_PATH"
  printf '%s\n' 'Updated generated package metadata files.'
fi
