#!/usr/bin/env bash

# Migrate Big Bang 3.x package values to the unified Big Bang 4.x package map.
# Requires Mike Farah yq v4.47.1 or newer: https://github.com/mikefarah/yq

set -euo pipefail

# BEGIN GENERATED PACKAGE METADATA
# Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml.
ROOT_PACKAGES=(
  alloy
  certManager
  eckOperator
  elasticsearchKibana
  fluentbit
  gatekeeper
  gatewayAPI
  grafana
  istioCNI
  istioCRDs
  istiod
  istioEgressGateway
  istioGateway
  kiali
  kyverno
  kyvernoPolicies
  kyvernoReporter
  loki
  monitoring
  neuvector
  prometheusOperatorCRDs
  renovate
  tempo
  twistlock
  ztunnel
)

ADDON_PACKAGES=(
  anchoreEnterprise
  argocd
  authservice
  externalSecrets
  fortify
  gitlab
  gitlabRunner
  harbor
  headlamp
  keycloak
  mattermost
  mattermostOperator
  metricsServer
  mimir
  minio
  minioOperator
  sonarqube
  thanos
  vault
  velero
)

BUILTIN_PACKAGE_METADATA=(
  "alloy|alloy"
  "certManager|cert-manager"
  "eckOperator|eck-operator"
  "elasticsearchKibana|elasticsearch-kibana"
  "fluentbit|fluentbit"
  "gatekeeper|gatekeeper"
  "gatewayAPI|gateway-api"
  "grafana|grafana"
  "istioCNI|istio-cni"
  "istioCRDs|istio-crds"
  "istiod|istiod"
  "istioEgressGateway|istio-egress-gateway"
  "istioGateway|istio-gateway"
  "kiali|kiali"
  "kyverno|kyverno"
  "kyvernoPolicies|kyverno-policies"
  "kyvernoReporter|kyverno-reporter"
  "loki|loki"
  "monitoring|monitoring"
  "neuvector|neuvector"
  "prometheusOperatorCRDs|prometheus-operator-crds"
  "renovate|renovate"
  "tempo|tempo"
  "twistlock|twistlock"
  "ztunnel|ztunnel"
  "anchoreEnterprise|anchore-enterprise"
  "argocd|argocd"
  "authservice|authservice"
  "externalSecrets|external-secrets"
  "fortify|fortify"
  "gitlab|gitlab"
  "gitlabRunner|gitlab-runner"
  "harbor|harbor"
  "headlamp|headlamp"
  "keycloak|keycloak"
  "mattermost|mattermost"
  "mattermostOperator|mattermost-operator"
  "metricsServer|metrics-server"
  "mimir|mimir"
  "minio|minio"
  "minioOperator|minio-operator"
  "sonarqube|sonarqube"
  "thanos|thanos"
  "vault|vault"
  "velero|velero"
)
# END GENERATED PACKAGE METADATA

usage() {
  cat <<'EOF'
Usage: migrate-values-3-to-4.sh --target {3|4} [OPTIONS] INPUT [INPUT ...]

Move Big Bang 3.x built-in package configuration from top-level and
addons.<name> paths to packages.<name>. Unless omitted for a secondary values
source, the output sets packageConfiguration.version to v1. Starting with Big
Bang 3.32, the 3.x chart uses it to interpret catalog package names as canonical
built-ins rather than existing custom packages.
With target 4, istio, networkPolicies, and routes values for built-in packages are also moved
under the bb-common subchart key.
Big Bang 4.x retains v1 as the default unified package contract; do not remove
it from a standalone migrated configuration when upgrading.
Target 3 performs only the unified package-path migration and retains the flat
bb-common library values and legacy hardening used by Big Bang 3.x. Target 4
also converts bb-common values to the subchart layout and removes legacy
hardening for Big Bang 4.x. Target 4 output must not be deployed to a 3.x
release.

Inputs are composed in order using Helm values precedence (later files win),
then migrated into one consolidated document. By default, migrated YAML is
written to standard output and the inputs are unchanged.
Package entries retain their first-appearance order in the composed input.
With --secret-key, exactly one decrypted Kubernetes Secret is accepted and its
envelope is preserved around the migrated values payload.
YAML anchors and aliases are expanded automatically and their anchor names are
reported. Expansion must preserve the resolved values structure.

Options:
  -t, --target {3|4}              Required target Big Bang major version.
  -o, --output FILE               Write migrated values to FILE.
  -i, --in-place                  Replace a single INPUT after creating
                                  INPUT.bak.
  -k, --secret-key KEY            Migrate values stored at data[KEY] or
                                  stringData[KEY] in one decrypted Kubernetes
                                  Secret.
      --omit-package-configuration
                                  Remove packageConfiguration from the output.
                                  Use only for a secondary values source when
                                  another composed source supplies
                                  packageConfiguration.version v1.
  -h, --help                      Show this help.

If both a legacy path and packages.<name> exist, they are recursively merged
and packages.<name> takes precedence. Unrecognized package entries are left
unchanged. The migration is idempotent.

Examples:
  scripts/migrate-values-3-to-4.sh --target 3 -o values-v1.yaml values.yaml
  scripts/migrate-values-3-to-4.sh --target 4 -o values-4.x.yaml values.yaml
  scripts/migrate-values-3-to-4.sh --target 4 values.yaml > values-4.x.yaml
  scripts/migrate-values-3-to-4.sh --target 4 --in-place values.yaml
  scripts/migrate-values-3-to-4.sh --target 4 --secret-key values.yaml secret.yaml
  scripts/migrate-values-3-to-4.sh --target 4 --omit-package-configuration \
    --output overlay-4.x.yaml overlay.yaml

For values embedded in a SOPS-encrypted Kubernetes Secret, use
scripts/migrate-sops-values-3-to-4.sh.
EOF
}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

decode_base64() {
  if printf '' | base64 --decode >/dev/null 2>&1; then
    base64 --decode
  else
    base64 -D
  fi
}

lower_package_name() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

# Mirror the chart's resourceName helper for package-name collision checks:
# replace non-word runs, trim and truncate, then apply Sprig's kebab casing.
package_resource_name() {
  printf '%s' "$1" \
    | sed -E 's/[^[:alnum:]_]+/-/g; s/^-//' \
    | cut -c 1-63 \
    | sed -E 's/-$//; s/([[:upper:]]+)([[:upper:]][[:lower:]])/\1-\2/g; s/([[:lower:][:digit:]])([[:upper:]])/\1-\2/g; s/_/-/g' \
    | tr '[:upper:]' '[:lower:]'
}

is_builtin_package() {
  local candidate=$1
  local package_name

  for package_name in "${ROOT_PACKAGES[@]}" "${ADDON_PACKAGES[@]}"; do
    [[ "$candidate" == "$package_name" ]] && return 0
  done
  return 1
}

is_root_package() {
  local candidate=$1
  local package_name

  for package_name in "${ROOT_PACKAGES[@]}"; do
    [[ "$candidate" == "$package_name" ]] && return 0
  done
  return 1
}

is_addon_package() {
  local candidate=$1
  local package_name

  [[ "$candidate" == "mattermostoperator" ]] && return 0
  for package_name in "${ADDON_PACKAGES[@]}"; do
    [[ "$candidate" == "$package_name" ]] && return 0
  done
  return 1
}

append_package_order() {
  local candidate=$1
  local package_name

  for package_name in "${PACKAGE_ORDER[@]}"; do
    [[ "$candidate" == "$package_name" ]] && return 0
  done
  PACKAGE_ORDER+=("$candidate")
}

capture_package_order() {
  local values_file=$1
  local top_level_name
  local package_name

  PACKAGE_ORDER=()
  while IFS= read -r top_level_name; do
    if is_root_package "$top_level_name"; then
      append_package_order "$top_level_name"
    elif [[ "$top_level_name" == "addons" ]]; then
      while IFS= read -r package_name; do
        if is_addon_package "$package_name"; then
          [[ "$package_name" == "mattermostoperator" ]] \
            && package_name=mattermostOperator
          append_package_order "$package_name"
        fi
      done < <(yq -r '.addons // {} | to_entries | .[].key' "$values_file")
    elif [[ "$top_level_name" == "packages" ]]; then
      while IFS= read -r package_name; do
        append_package_order "$package_name"
      done < <(yq -r '.packages // {} | to_entries | .[].key' "$values_file")
    fi
  done < <(yq -r 'to_entries | .[].key' "$values_file")
}

reorder_packages() {
  local values_file=$1
  local package_name
  local package_order_yaml

  while IFS= read -r package_name; do
    append_package_order "$package_name"
  done < <(yq -r '.packages // {} | to_entries | .[].key' "$values_file")

  [[ ${#PACKAGE_ORDER[@]} -gt 0 ]] || return 0
  package_order_yaml=$(printf '%s\n' "${PACKAGE_ORDER[@]}" \
    | jq -Rn '[inputs]' \
    | yq -P)
  PACKAGE_ORDER_YAML="$package_order_yaml" yq -i '
    .packages as $packages |
    ($packages | to_entries) as $entries |
    (env(PACKAGE_ORDER_YAML) |
      map(. as $name | $entries[] | select(.key == $name)) |
      from_entries) as $ordered |
    .packages = $ordered |
    .packages style=""
  ' "$values_file"
}

validate_values_file() {
  local values_file=$1
  local display_name=${2:-$1}
  local document_count

  document_count=$(yq eval-all --no-doc '1' "$values_file" 2>/dev/null | wc -l | tr -d '[:space:]') \
    || fail "input is not valid YAML: $display_name"
  [[ "$document_count" == "1" ]] \
    || fail "multiple YAML documents are not supported: $display_name"
  yq -e 'tag == "!!map"' "$values_file" >/dev/null 2>&1 \
    || fail "the values document root must be a YAML mapping: $display_name"
  yq -e 'has("sops") and (.sops | tag == "!!map")' "$values_file" >/dev/null 2>&1 \
    && fail "SOPS-encrypted input is not supported by this command: $display_name; use scripts/migrate-sops-values-3-to-4.sh"
  yq --yaml-fix-merge-anchor-to-spec=true -e \
    'explode(.) | ((.packages == null) or (.packages | tag == "!!map"))' "$values_file" >/dev/null 2>&1 \
    || fail "packages must be a YAML mapping: $display_name"
  yq --yaml-fix-merge-anchor-to-spec=true -e \
    'explode(.) | ((.addons == null) or (.addons | tag == "!!map"))' "$values_file" >/dev/null 2>&1 \
    || fail "addons must be a YAML mapping: $display_name"
  yq --yaml-fix-merge-anchor-to-spec=true -e \
    'explode(.) | ((.packageConfiguration == null) or (.packageConfiguration | tag == "!!map"))' "$values_file" >/dev/null 2>&1 \
    || fail "packageConfiguration must be a YAML mapping: $display_name"
  yq --yaml-fix-merge-anchor-to-spec=true -e \
    'explode(.) | ((.packageConfiguration.version == null) or (.packageConfiguration.version == "v1"))' "$values_file" >/dev/null 2>&1 \
    || fail "packageConfiguration.version must be v1: $display_name"
}

OUTPUT_FILE=""
IN_PLACE=false
SECRET_VALUES_KEY=""
TARGET_VERSION=""
OMIT_PACKAGE_CONFIGURATION=false
INPUT_FILES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--target)
      [[ $# -ge 2 ]] || fail "$1 requires 3 or 4"
      [[ -z "$TARGET_VERSION" ]] || fail "--target may only be specified once"
      case "$2" in
        3|4) TARGET_VERSION=$2 ;;
        *) fail "$1 must be 3 or 4" ;;
      esac
      shift 2
      ;;
    -o|--output)
      [[ $# -ge 2 ]] || fail "$1 requires a file path"
      OUTPUT_FILE=$2
      shift 2
      ;;
    -i|--in-place)
      IN_PLACE=true
      shift
      ;;
    -k|--secret-key)
      [[ $# -ge 2 ]] || fail "$1 requires a Secret key"
      [[ -n "$2" ]] || fail "$1 requires a non-empty Secret key"
      SECRET_VALUES_KEY=$2
      shift 2
      ;;
    --omit-package-configuration)
      OMIT_PACKAGE_CONFIGURATION=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      fail "unknown option: $1"
      ;;
    *)
      INPUT_FILES+=("$1")
      shift
      ;;
  esac
done

[[ -n "$TARGET_VERSION" ]] || fail "--target is required and must be 3 or 4"
[[ ${#INPUT_FILES[@]} -gt 0 ]] || fail "at least one input values file is required"
[[ -z "$SECRET_VALUES_KEY" || ${#INPUT_FILES[@]} -eq 1 ]] \
  || fail "--secret-key requires exactly one input Secret"
command -v yq >/dev/null 2>&1 || fail "Mike Farah yq v4 is required"
[[ "$(yq --version 2>/dev/null)" =~ version\ v4\. ]] || fail "Mike Farah yq v4 is required"
yq --yaml-fix-merge-anchor-to-spec=true --null-input '.' >/dev/null 2>&1 \
  || fail "Mike Farah yq v4.47.1 or newer with --yaml-fix-merge-anchor-to-spec support is required"
command -v jq >/dev/null 2>&1 || fail "jq is required"

if [[ "$IN_PLACE" == true && -n "$OUTPUT_FILE" ]]; then
  fail "--in-place and --output cannot be used together"
fi
if [[ "$IN_PLACE" == true && ${#INPUT_FILES[@]} -ne 1 ]]; then
  fail "--in-place requires exactly one input file"
fi
if [[ -n "$OUTPUT_FILE" && -d "$OUTPUT_FILE" ]]; then
  fail "output path must be a file, not a directory: $OUTPUT_FILE"
fi

for input_file in "${INPUT_FILES[@]}"; do
  [[ -f "$input_file" ]] || fail "input file does not exist: $input_file"
  [[ -r "$input_file" ]] || fail "input file is not readable: $input_file"

  if [[ -n "$SECRET_VALUES_KEY" ]]; then
    document_count=$(yq eval-all --no-doc '1' "$input_file" 2>/dev/null | wc -l | tr -d '[:space:]') \
      || fail "input is not valid YAML: $input_file"
    [[ "$document_count" == "1" ]] \
      || fail "multiple YAML documents are not supported: $input_file"
    yq -e 'tag == "!!map"' "$input_file" >/dev/null 2>&1 \
      || fail "the Secret document root must be a YAML mapping: $input_file"
    yq -e 'has("sops") and (.sops | tag == "!!map")' "$input_file" >/dev/null 2>&1 \
      && fail "SOPS-encrypted input is not supported by this command: $input_file; use scripts/migrate-sops-values-3-to-4.sh"
    yq -e '.kind == "Secret"' "$input_file" >/dev/null 2>&1 \
      || fail "--secret-key input must be a Kubernetes Secret: $input_file"
    yq --yaml-fix-merge-anchor-to-spec=true -e \
      'explode(.) | ((.stringData == null) or ((.stringData | tag) == "!!map"))' "$input_file" >/dev/null 2>&1 \
      || fail "Secret stringData must be a mapping: $input_file"
    yq --yaml-fix-merge-anchor-to-spec=true -e \
      'explode(.) | ((.data == null) or ((.data | tag) == "!!map"))' "$input_file" >/dev/null 2>&1 \
      || fail "Secret data must be a mapping: $input_file"
  else
    validate_values_file "$input_file"
  fi
done

if [[ -n "$OUTPUT_FILE" ]]; then
  for input_file in "${INPUT_FILES[@]}"; do
    if [[ "$OUTPUT_FILE" == "$input_file" ]] \
      || [[ -e "$OUTPUT_FILE" && "$OUTPUT_FILE" -ef "$input_file" ]]; then
      fail "output refers to an input file; use --in-place with a single input to replace it safely"
    fi
  done
fi

umask 077
WORK_FILE=$(mktemp "${TMPDIR:-/tmp}/bigbang-values-migration.XXXXXX")
SECRET_WORK_FILE=$(mktemp "${TMPDIR:-/tmp}/bigbang-secret-migration.XXXXXX")
SECRET_VALUE_FILE=$(mktemp "${TMPDIR:-/tmp}/bigbang-secret-value.XXXXXX")
BASE64_INPUT=$(mktemp "${TMPDIR:-/tmp}/bigbang-secret-base64.XXXXXX")
EXPANDED_FILE=$(mktemp "${TMPDIR:-/tmp}/bigbang-values-expanded.XXXXXX")
BEFORE_EXPANSION_JSON=$(mktemp "${TMPDIR:-/tmp}/bigbang-values-before-expansion.XXXXXX")
AFTER_EXPANSION_JSON=$(mktemp "${TMPDIR:-/tmp}/bigbang-values-after-expansion.XXXXXX")
trap 'rm -f "$WORK_FILE" "$SECRET_WORK_FILE" "$SECRET_VALUE_FILE" "$BASE64_INPUT" "$EXPANDED_FILE" "$BEFORE_EXPANSION_JSON" "$AFTER_EXPANSION_JSON"' EXIT

expand_yaml_anchors() {
  local values_file=$1
  local display_name=$2
  local anchor_name
  local anchor_names_output
  local anchor_names=()

  anchor_names_output=$(yq -r \
    '[.. | anchor] | map(select(. != "")) | unique | .[]' "$values_file")
  while IFS= read -r anchor_name; do
    [[ -n "$anchor_name" ]] && anchor_names+=("$anchor_name")
  done <<<"$anchor_names_output"

  [[ ${#anchor_names[@]} -gt 0 ]] || return 0

  yq --yaml-fix-merge-anchor-to-spec=true -o=json -I=0 '.' "$values_file" \
    | jq -cS '.' >"$BEFORE_EXPANSION_JSON"
  yq --yaml-fix-merge-anchor-to-spec=true 'explode(.)' \
    "$values_file" >"$EXPANDED_FILE"
  yq --yaml-fix-merge-anchor-to-spec=true -o=json -I=0 '.' "$EXPANDED_FILE" \
    | jq -cS '.' >"$AFTER_EXPANSION_JSON"
  cmp -s "$BEFORE_EXPANSION_JSON" "$AFTER_EXPANSION_JSON" \
    || fail "expanding YAML anchors changed the resolved values structure: $display_name"
  cp "$EXPANDED_FILE" "$values_file"

  printf 'Warning: expanded YAML anchors and aliases in %s; they will not be preserved in the output.\n' \
    "$display_name" >&2
  printf 'Expanded anchors:\n' >&2
  printf '  %s\n' "${anchor_names[@]}" >&2
}

if [[ -n "$SECRET_VALUES_KEY" ]]; then
  cp "${INPUT_FILES[0]}" "$SECRET_WORK_FILE"
  expand_yaml_anchors "$SECRET_WORK_FILE" "${INPUT_FILES[0]} Secret envelope"
  HAS_STRING_DATA=$(SECRET_VALUES_KEY="$SECRET_VALUES_KEY" yq -r \
    '(.stringData // {}) | has(strenv(SECRET_VALUES_KEY))' "$SECRET_WORK_FILE")
  HAS_DATA=$(SECRET_VALUES_KEY="$SECRET_VALUES_KEY" yq -r \
    '(.data // {}) | has(strenv(SECRET_VALUES_KEY))' "$SECRET_WORK_FILE")

  if [[ "$HAS_STRING_DATA" == true && "$HAS_DATA" == true ]]; then
    fail "Secret key ${SECRET_VALUES_KEY} exists in both data and stringData"
  elif [[ "$HAS_STRING_DATA" == true ]]; then
    SECRET_VALUES_FIELD=stringData
    SECRET_VALUES_KEY="$SECRET_VALUES_KEY" yq -r -0 \
      '.stringData[strenv(SECRET_VALUES_KEY)]' "$SECRET_WORK_FILE" \
      | tr -d '\000' >"$WORK_FILE"
  elif [[ "$HAS_DATA" == true ]]; then
    SECRET_VALUES_FIELD=data
    SECRET_VALUES_KEY="$SECRET_VALUES_KEY" yq -r -0 \
      '.data[strenv(SECRET_VALUES_KEY)]' "$SECRET_WORK_FILE" \
      | tr -d '\000' \
      | tr -d '[:space:]' >"$BASE64_INPUT"
    if ! grep -Eq '^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$' \
      "$BASE64_INPUT" \
      || ! decode_base64 <"$BASE64_INPUT" >"$WORK_FILE"; then
      fail "data.${SECRET_VALUES_KEY} is not valid base64"
    fi
  else
    fail "Secret does not contain ${SECRET_VALUES_KEY} in data or stringData"
  fi
  validate_values_file "$WORK_FILE" "${INPUT_FILES[0]}:${SECRET_VALUES_KEY}"
elif [[ ${#INPUT_FILES[@]} -eq 1 ]]; then
  cp "${INPUT_FILES[0]}" "$WORK_FILE"
else
  yq --yaml-fix-merge-anchor-to-spec=true eval-all \
    '. as $item ireduce ({}; . * $item)' "${INPUT_FILES[@]}" >"$WORK_FILE"
fi

if [[ -n "$SECRET_VALUES_KEY" ]]; then
  ANCHOR_DISPLAY_NAME="${INPUT_FILES[0]}:${SECRET_VALUES_KEY}"
elif [[ ${#INPUT_FILES[@]} -eq 1 ]]; then
  ANCHOR_DISPLAY_NAME="${INPUT_FILES[0]}"
else
  ANCHOR_DISPLAY_NAME="composed values input"
fi
expand_yaml_anchors "$WORK_FILE" "$ANCHOR_DISPLAY_NAME"

# Before v1 is enabled, every packages.<name> entry has the 3.x custom-package
# meaning. Refuse both exact and normalized collisions before enabling v1 so
# migration cannot produce values that the chart will reject. Values already
# using v1 receive the same normalized collision validation as chart rendering.
CANONICAL_PACKAGES_ENABLED=false
if [[ "$OMIT_PACKAGE_CONFIGURATION" == true ]] \
  || yq -e '.packageConfiguration.version == "v1"' "$WORK_FILE" >/dev/null 2>&1; then
  CANONICAL_PACKAGES_ENABLED=true
fi

CUSTOM_PACKAGE_NAMES=()
CUSTOM_PACKAGE_RESOURCE_NAMES=()
while IFS= read -r package_name; do
  if is_builtin_package "$package_name"; then
    if [[ "$CANONICAL_PACKAGES_ENABLED" != true ]]; then
      fail "packages.${package_name} is an existing 3.x custom package that conflicts with a canonical built-in name; rename it or explicitly set packageConfiguration.version to v1 before migrating"
    fi
    continue
  fi

  package_lower=$(lower_package_name "$package_name")
  package_resource_identity=$(package_resource_name "$package_name")

  for package_metadata in "${BUILTIN_PACKAGE_METADATA[@]}"; do
    builtin_name=${package_metadata%%|*}
    template_directory=${package_metadata#*|}
    builtin_lower=$(lower_package_name "$builtin_name")
    builtin_resource_name=$(package_resource_name "$builtin_name")
    template_directory_lower=$(lower_package_name "$template_directory")

    if [[ "$package_lower" == "$builtin_lower" \
      || "$package_lower" == "$builtin_resource_name" \
      || "$package_lower" == "$template_directory_lower" \
      || "$package_resource_identity" == "$builtin_lower" \
      || "$package_resource_identity" == "$builtin_resource_name" \
      || "$package_resource_identity" == "$template_directory_lower" ]]; then
      fail "packages.${package_name} conflicts with built-in package packages.${builtin_name}; use the canonical name packages.${builtin_name}"
    fi
  done

  for custom_index in "${!CUSTOM_PACKAGE_RESOURCE_NAMES[@]}"; do
    if [[ "$package_resource_identity" == "${CUSTOM_PACKAGE_RESOURCE_NAMES[$custom_index]}" ]]; then
      fail "packages.${CUSTOM_PACKAGE_NAMES[$custom_index]} and packages.${package_name} normalize to the same package identity"
    fi
  done
  CUSTOM_PACKAGE_NAMES+=("$package_name")
  CUSTOM_PACKAGE_RESOURCE_NAMES+=("$package_resource_identity")
done < <(yq -r '.packages // {} | keys | .[]' "$WORK_FILE")

capture_package_order "$WORK_FILE"

if [[ "$OMIT_PACKAGE_CONFIGURATION" == true ]]; then
  yq -i 'del(.packageConfiguration)' "$WORK_FILE"
else
  yq -i '.packageConfiguration = (.packageConfiguration // {}) | .packageConfiguration.version = "v1"' "$WORK_FILE"
fi

MIGRATED_PATHS=()

for package_name in "${ROOT_PACKAGES[@]}"; do
  if PACKAGE_NAME="$package_name" yq -e 'has(strenv(PACKAGE_NAME))' "$WORK_FILE" >/dev/null 2>&1; then
    PACKAGE_NAME="$package_name" yq -i '
      .packages = (.packages // {}) |
      .packages[strenv(PACKAGE_NAME)] =
        ((.[strenv(PACKAGE_NAME)] // {}) * (.packages[strenv(PACKAGE_NAME)] // {})) |
      del(.[strenv(PACKAGE_NAME)])
    ' "$WORK_FILE"
    MIGRATED_PATHS+=("$package_name -> packages.$package_name")
  fi
done

# The deprecated lowercase spelling is still accepted by the 3.x templates.
# Normalize it first so the supported spelling, and then the canonical package
# path, retain their existing precedence.
if yq -e '.addons | has("mattermostoperator")' "$WORK_FILE" >/dev/null 2>&1; then
  yq -i '
    .addons.mattermostOperator =
      ((.addons.mattermostoperator // {}) * (.addons.mattermostOperator // {})) |
    del(.addons.mattermostoperator)
  ' "$WORK_FILE"
  MIGRATED_PATHS+=("addons.mattermostoperator -> packages.mattermostOperator")
fi

for package_name in "${ADDON_PACKAGES[@]}"; do
  if PACKAGE_NAME="$package_name" yq -e '.addons | has(strenv(PACKAGE_NAME))' "$WORK_FILE" >/dev/null 2>&1; then
    PACKAGE_NAME="$package_name" yq -i '
      .packages = (.packages // {}) |
      .packages[strenv(PACKAGE_NAME)] =
        ((.addons[strenv(PACKAGE_NAME)] // {}) * (.packages[strenv(PACKAGE_NAME)] // {})) |
      del(.addons[strenv(PACKAGE_NAME)])
    ' "$WORK_FILE"
    MIGRATED_PATHS+=("addons.$package_name -> packages.$package_name")
  fi
done

SERVICE_ENTRY_REVIEW=()
if [[ "$TARGET_VERSION" == 4 ]]; then
  # Big Bang 4.x packages consume bb-common as a subchart. Move the values that
  # belonged to the former library chart into the subchart's values scope after
  # legacy and canonical package paths have been merged.
  for package_name in "${ROOT_PACKAGES[@]}" "${ADDON_PACKAGES[@]}"; do
    for value_key in istio networkPolicies routes; do
      if PACKAGE_NAME="$package_name" VALUE_KEY="$value_key" yq -e '
        (.packages[strenv(PACKAGE_NAME)].values | tag == "!!map") and
        (.packages[strenv(PACKAGE_NAME)].values | has(strenv(VALUE_KEY)))
      ' "$WORK_FILE" >/dev/null 2>&1; then
        PACKAGE_NAME="$package_name" VALUE_KEY="$value_key" yq -i '
          .packages[strenv(PACKAGE_NAME)].values |= (
            ."bb-common" = (."bb-common" // {}) |
            ."bb-common"[strenv(VALUE_KEY)] =
              ((.[strenv(VALUE_KEY)] // {}) *
               (."bb-common"[strenv(VALUE_KEY)] // {})) |
            del(.[strenv(VALUE_KEY)])
          )
        ' "$WORK_FILE"

        MIGRATED_PATHS+=(
          "packages.$package_name.values.$value_key -> packages.$package_name.values.bb-common.$value_key"
        )
      fi
    done
  done

  # Remove legacy hardening after preserving its custom resources in the 4.x
  # bb-common locations.
  for package_name in "${ROOT_PACKAGES[@]}" "${ADDON_PACKAGES[@]}"; do
    PACKAGE_NAME="$package_name" yq -e \
      '.packages[strenv(PACKAGE_NAME)].values.bb-common.istio | tag == "!!map"' \
      "$WORK_FILE" >/dev/null 2>&1 || continue

    hardened_se_names=$(PACKAGE_NAME="$package_name" yq -r '
      (.packages[strenv(PACKAGE_NAME)].values.bb-common.istio.hardened.customServiceEntries // [])
      | select(length > 0)
      | map(.name // "(unnamed)") | join(", ")
    ' "$WORK_FILE")
    hardened_authz_count=$(PACKAGE_NAME="$package_name" yq -r '
      (.packages[strenv(PACKAGE_NAME)].values.bb-common.istio.hardened.customAuthorizationPolicies // [])
      | length
    ' "$WORK_FILE")

    PACKAGE_NAME="$package_name" yq -i '
      with(.packages[strenv(PACKAGE_NAME)].values.bb-common.istio;
          with(select((.hardened.customServiceEntries // []) | length > 0);
            .serviceEntries.custom =
              (.hardened.customServiceEntries + (.serviceEntries.custom // [])))
        | with(select((.hardened.customAuthorizationPolicies // []) | length > 0);
            .authorizationPolicies.custom =
              (.hardened.customAuthorizationPolicies + (.authorizationPolicies.custom // [])))
        | del(.hardened)
      )
    ' "$WORK_FILE"

    if [[ -n "$hardened_se_names" ]]; then
      MIGRATED_PATHS+=("packages.$package_name.values.bb-common.istio.hardened.customServiceEntries -> serviceEntries.custom")
      if [[ "$package_name" != "istiod" ]]; then
        SERVICE_ENTRY_REVIEW+=("packages.$package_name.values.bb-common.istio.serviceEntries.custom: $hardened_se_names")
      fi
    fi
    if [[ "$hardened_authz_count" -gt 0 ]]; then
      MIGRATED_PATHS+=("packages.$package_name.values.bb-common.istio.hardened.customAuthorizationPolicies -> authorizationPolicies.custom")
    fi
  done

  if yq -e '.packages.istiod.values | has("hardened")' "$WORK_FILE" >/dev/null 2>&1; then
    yq -i 'del(.packages.istiod.values.hardened)' "$WORK_FILE"
    yq -i 'del(.packages.istiod.values | select(tag == "!!map" and length == 0))' "$WORK_FILE"
    MIGRATED_PATHS+=("packages.istiod.values.hardened -> removed (hardening deprecated in 4.x)")
  fi
fi

if yq -e '(.addons | tag == "!!map") and (.addons | length == 0)' "$WORK_FILE" >/dev/null 2>&1; then
  yq -i 'del(.addons)' "$WORK_FILE"
fi

reorder_packages "$WORK_FILE"

RESULT_FILE=$WORK_FILE
if [[ -n "$SECRET_VALUES_KEY" ]]; then
  if [[ "$SECRET_VALUES_FIELD" == data ]]; then
    base64 <"$WORK_FILE" | tr -d '\n' >"$SECRET_VALUE_FILE"
  else
    cp "$WORK_FILE" "$SECRET_VALUE_FILE"
  fi
  SECRET_VALUES_FIELD="$SECRET_VALUES_FIELD" \
  SECRET_VALUES_KEY="$SECRET_VALUES_KEY" \
  SECRET_VALUE_FILE="$SECRET_VALUE_FILE" \
    yq -i '
      .[strenv(SECRET_VALUES_FIELD)][strenv(SECRET_VALUES_KEY)] =
        load_str(strenv(SECRET_VALUE_FILE))
    ' "$SECRET_WORK_FILE"
  RESULT_FILE=$SECRET_WORK_FILE
fi

if [[ "$IN_PLACE" == true ]]; then
  INPUT_FILE=${INPUT_FILES[0]}
  BACKUP_FILE="${INPUT_FILE}.bak"
  [[ ! -e "$BACKUP_FILE" ]] || fail "backup already exists: $BACKUP_FILE"
  cp -p "$INPUT_FILE" "$BACKUP_FILE"
  cp "$RESULT_FILE" "$INPUT_FILE"
  printf 'Migrated %s; backup written to %s\n' "$INPUT_FILE" "$BACKUP_FILE" >&2
elif [[ -n "$OUTPUT_FILE" ]]; then
  cp "$RESULT_FILE" "$OUTPUT_FILE"
  printf 'Migrated values written to %s\n' "$OUTPUT_FILE" >&2
else
  cat "$RESULT_FILE"
fi

if [[ ${#MIGRATED_PATHS[@]} -eq 0 ]]; then
  printf 'No legacy built-in package paths found.\n' >&2
else
  printf 'Migrated package paths:\n' >&2
  printf '  %s\n' "${MIGRATED_PATHS[@]}" >&2
fi

if [[ ${#SERVICE_ENTRY_REVIEW[@]} -gt 0 ]]; then
  printf '\nReview: the following ServiceEntries were migrated from hardened.customServiceEntries and\n' >&2
  printf 'remain cluster-wide (istio.serviceEntries.custom). If namespace-scoped egress is sufficient,\n' >&2
  printf "consider moving each to that package's bb-common.routes.outbound instead:\n" >&2
  printf '  %s\n' "${SERVICE_ENTRY_REVIEW[@]}" >&2
  printf '\nReference: https://docs-bigbang.dso.mil/latest/library-charts/bb-common/docs/routes/\n' >&2
fi
