#!/usr/bin/env bash

# Migrate Big Bang 3.x package values to the unified Big Bang 4.x package map.
# Requires Mike Farah yq v4: https://github.com/mikefarah/yq

set -euo pipefail

# BEGIN GENERATED PACKAGE METADATA
# Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml.
ROOT_PACKAGES=(
  istioCNI
  istioCRDs
  gatewayAPI
  istiod
  istioGateway
  ztunnel
  kiali
  gatekeeper
  kyverno
  kyvernoPolicies
  kyvernoReporter
  elasticsearchKibana
  eckOperator
  fluentbit
  alloy
  loki
  neuvector
  tempo
  prometheusOperatorCRDs
  monitoring
  grafana
  twistlock
  bbctl
  renovate
)

ADDON_PACKAGES=(
  argocd
  authservice
  minioOperator
  minio
  gitlab
  gitlabRunner
  sonarqube
  fortify
  anchoreEnterprise
  mattermostOperator
  mattermost
  velero
  keycloak
  vault
  metricsServer
  harbor
  headlamp
  thanos
  externalSecrets
  mimir
)
# END GENERATED PACKAGE METADATA

usage() {
  cat <<'EOF'
Usage: migrate-values-3-to-4.sh [OPTIONS] INPUT [INPUT ...]

Move Big Bang 3.x built-in package configuration from top-level and
addons.<name> paths to the Big Bang 4.x packages.<name> paths. The output sets
packageConfiguration.version to v1. Big Bang 3.x uses it to interpret catalog
package names as canonical built-ins rather than existing custom packages.
Big Bang 4.x retains v1 as the default unified package contract; do not remove
it from the migrated output when upgrading.

Inputs are composed in order using Helm values precedence (later files win),
then migrated into one consolidated document. By default, migrated YAML is
written to standard output and the inputs are unchanged.

Options:
  -o, --output FILE  Write migrated values to FILE.
  -i, --in-place     Replace a single INPUT after creating INPUT.bak.
  -h, --help         Show this help.

If both a legacy path and packages.<name> exist, they are recursively merged
and packages.<name> takes precedence. Unrecognized package entries are left
unchanged. The migration is idempotent.

Examples:
  scripts/migrate-values-3-to-4.sh values.yaml > values-4.x.yaml
  scripts/migrate-values-3-to-4.sh base.yaml production.yaml > values-4.x.yaml
  scripts/migrate-values-3-to-4.sh -o values-4.x.yaml values.yaml
  scripts/migrate-values-3-to-4.sh --in-place values.yaml
EOF
}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

OUTPUT_FILE=""
IN_PLACE=false
INPUT_FILES=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output)
      [[ $# -ge 2 ]] || fail "$1 requires a file path"
      OUTPUT_FILE=$2
      shift 2
      ;;
    -i|--in-place)
      IN_PLACE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      fail "unknown option: $1"
      ;;
    *)
      INPUT_FILES+=("$1")
      shift
      ;;
  esac
done

[[ ${#INPUT_FILES[@]} -gt 0 ]] || fail "at least one input values file is required"
command -v yq >/dev/null 2>&1 || fail "Mike Farah yq v4 is required"
[[ "$(yq --version 2>/dev/null)" =~ version\ v4\. ]] || fail "Mike Farah yq v4 is required"

if [[ "$IN_PLACE" == true && -n "$OUTPUT_FILE" ]]; then
  fail "--in-place and --output cannot be used together"
fi
if [[ "$IN_PLACE" == true && ${#INPUT_FILES[@]} -ne 1 ]]; then
  fail "--in-place requires exactly one input file"
fi

for input_file in "${INPUT_FILES[@]}"; do
  [[ -f "$input_file" ]] || fail "input file does not exist: $input_file"
  [[ -r "$input_file" ]] || fail "input file is not readable: $input_file"

  document_count=$(yq eval-all --no-doc '1' "$input_file" 2>/dev/null | wc -l | tr -d '[:space:]') \
    || fail "input is not valid YAML: $input_file"
  [[ "$document_count" == "1" ]] \
    || fail "multiple YAML documents are not supported: $input_file"
  yq -e 'tag == "!!map"' "$input_file" >/dev/null 2>&1 \
    || fail "the values document root must be a YAML mapping: $input_file"
  yq -e 'has("sops") and (.sops | tag == "!!map")' "$input_file" >/dev/null 2>&1 \
    && fail "SOPS-encrypted input is not supported: $input_file; decrypt it with sops, migrate the plaintext, then re-encrypt it"
  yq -e '[.. | anchor] | map(select(. != "")) | length == 0' "$input_file" >/dev/null 2>&1 \
    || fail "YAML anchors and aliases are not supported: $input_file; expand them before migrating"
  yq -e '(.packages == null) or (.packages | tag == "!!map")' "$input_file" >/dev/null 2>&1 \
    || fail "packages must be a YAML mapping: $input_file"
  yq -e '(.addons == null) or (.addons | tag == "!!map")' "$input_file" >/dev/null 2>&1 \
    || fail "addons must be a YAML mapping: $input_file"
  yq -e '(.packageConfiguration == null) or (.packageConfiguration | tag == "!!map")' "$input_file" >/dev/null 2>&1 \
    || fail "packageConfiguration must be a YAML mapping: $input_file"
  yq -e '(.packageConfiguration.version == null) or (.packageConfiguration.version == "v1")' "$input_file" >/dev/null 2>&1 \
    || fail "packageConfiguration.version must be v1: $input_file"
done

if [[ -n "$OUTPUT_FILE" ]]; then
  for input_file in "${INPUT_FILES[@]}"; do
    if [[ "$OUTPUT_FILE" == "$input_file" ]] \
      || [[ -e "$OUTPUT_FILE" && "$OUTPUT_FILE" -ef "$input_file" ]]; then
      fail "output refers to an input file; use --in-place with a single input to replace it safely"
    fi
  done
fi

WORK_FILE=$(mktemp "${TMPDIR:-/tmp}/bigbang-values-migration.XXXXXX")
trap 'rm -f "$WORK_FILE"' EXIT
if [[ ${#INPUT_FILES[@]} -eq 1 ]]; then
  cp "${INPUT_FILES[0]}" "$WORK_FILE"
else
  yq eval-all '. as $item ireduce ({}; . * $item)' "${INPUT_FILES[@]}" >"$WORK_FILE"
fi

# Before v1 is enabled, every packages.<name> entry has the 3.x custom-package
# meaning. Refuse to reinterpret an exact built-in name without explicit user
# intent; schema shape cannot reliably distinguish the two contracts.
if ! yq -e '.packageConfiguration.version == "v1"' "$WORK_FILE" >/dev/null 2>&1; then
  for package_name in "${ROOT_PACKAGES[@]}" "${ADDON_PACKAGES[@]}"; do
    if PACKAGE_NAME="$package_name" yq -e '.packages | has(strenv(PACKAGE_NAME))' "$WORK_FILE" >/dev/null 2>&1; then
      fail "packages.${package_name} is an existing 3.x custom package that conflicts with a canonical built-in name; rename it or explicitly set packageConfiguration.version to v1 before migrating"
    fi
  done
fi

yq -i '.packageConfiguration = (.packageConfiguration // {}) | .packageConfiguration.version = "v1"' "$WORK_FILE"

MIGRATED_PATHS=()

for package_name in "${ROOT_PACKAGES[@]}"; do
  if PACKAGE_NAME="$package_name" yq -e 'has(strenv(PACKAGE_NAME))' "$WORK_FILE" >/dev/null 2>&1; then
    PACKAGE_NAME="$package_name" yq -i '
      .packages = (.packages // {}) |
      .packages[strenv(PACKAGE_NAME)] =
        ((.[strenv(PACKAGE_NAME)] // {}) * (.packages[strenv(PACKAGE_NAME)] // {})) |
      del(.[strenv(PACKAGE_NAME)])
    ' "$WORK_FILE"
    MIGRATED_PATHS+=("$package_name -> packages.$package_name")
  fi
done

# The deprecated lowercase spelling is still accepted by the 3.x templates.
# Normalize it first so the supported spelling, and then the canonical package
# path, retain their existing precedence.
if yq -e '.addons | has("mattermostoperator")' "$WORK_FILE" >/dev/null 2>&1; then
  yq -i '
    .addons.mattermostOperator =
      ((.addons.mattermostoperator // {}) * (.addons.mattermostOperator // {})) |
    del(.addons.mattermostoperator)
  ' "$WORK_FILE"
  MIGRATED_PATHS+=("addons.mattermostoperator -> packages.mattermostOperator")
fi

for package_name in "${ADDON_PACKAGES[@]}"; do
  if PACKAGE_NAME="$package_name" yq -e '.addons | has(strenv(PACKAGE_NAME))' "$WORK_FILE" >/dev/null 2>&1; then
    PACKAGE_NAME="$package_name" yq -i '
      .packages = (.packages // {}) |
      .packages[strenv(PACKAGE_NAME)] =
        ((.addons[strenv(PACKAGE_NAME)] // {}) * (.packages[strenv(PACKAGE_NAME)] // {})) |
      del(.addons[strenv(PACKAGE_NAME)])
    ' "$WORK_FILE"
    MIGRATED_PATHS+=("addons.$package_name -> packages.$package_name")
  fi
done

if yq -e '(.addons | tag == "!!map") and (.addons | length == 0)' "$WORK_FILE" >/dev/null 2>&1; then
  yq -i 'del(.addons)' "$WORK_FILE"
fi

if [[ "$IN_PLACE" == true ]]; then
  INPUT_FILE=${INPUT_FILES[0]}
  BACKUP_FILE="${INPUT_FILE}.bak"
  [[ ! -e "$BACKUP_FILE" ]] || fail "backup already exists: $BACKUP_FILE"
  cp -p "$INPUT_FILE" "$BACKUP_FILE"
  cp "$WORK_FILE" "$INPUT_FILE"
  printf 'Migrated %s; backup written to %s\n' "$INPUT_FILE" "$BACKUP_FILE" >&2
elif [[ -n "$OUTPUT_FILE" ]]; then
  cp "$WORK_FILE" "$OUTPUT_FILE"
  printf 'Migrated values written to %s\n' "$OUTPUT_FILE" >&2
else
  cat "$WORK_FILE"
fi

if [[ ${#MIGRATED_PATHS[@]} -eq 0 ]]; then
  printf 'No legacy built-in package paths found.\n' >&2
else
  printf 'Migrated package paths:\n' >&2
  printf '  %s\n' "${MIGRATED_PATHS[@]}" >&2
fi
