values.yaml: |
    registryCredentials:
      registry: "###ZARF_REGISTRY###"
      username: "zarf-pull"
      password: "${ZARF_PULL}"
    git:
      existingSecret: "private-git-server"	# -- Chart created secrets with user defined values
      credentials:
        username: "zarf-git-user" # -- HTTP git credentials, both username and password must be provided
        password: "${ZARF_GIT_USER}"

