{{- if and (ne .Values.packages.addons.gitlab.redis.password "") .Values.packages.addons.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-secret-bb
  namespace: gitlab
type: Opaque
data:
  secret: {{ .Values.packages.addons.gitlab.redis.password | b64enc }}
{{- end }}
