{{- if and .Values.packages.addons.gitlab.smtp.password .Values.packages.addons.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-smtp-password
  namespace: gitlab
type: Opaque
data:
  password: {{ .Values.packages.addons.gitlab.smtp.password | b64enc }}
{{- end }}
