{{- if .Values.packages.addons.gitlab.enabled }}
{{- if or .Values.packages.addons.gitlab.objectStorage.region .Values.packages.addons.gitlab.objectStorage.endpoint }}
{{- if and (ne .Values.packages.addons.gitlab.objectStorage.iamProfile "") (ne .Values.packages.addons.gitlab.objectStorage.accessKey "") }}{{- fail "Must choose to use an IAM profile OR an AWS accessKey/accessSecret at .Values.packages.addons.gitlab.objectStorage" }}{{- end }}
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-object-storage
    namespace: gitlab
type: kubernetes.io/opaque
stringData:
    rails: |-
      provider: AWS
      region: {{ .Values.packages.addons.gitlab.objectStorage.region }}
      {{- if ne .Values.packages.addons.gitlab.objectStorage.iamProfile "" }}
      use_iam_profile: true
      {{- else if eq .Values.packages.addons.gitlab.objectStorage.iamProfile "" }}
      aws_access_key_id: {{ .Values.packages.addons.gitlab.objectStorage.accessKey }}
      aws_secret_access_key: {{ .Values.packages.addons.gitlab.objectStorage.accessSecret }}
      {{- end }}
      {{- if .Values.packages.addons.gitlab.objectStorage.endpoint }}
      endpoint: "{{ .Values.packages.addons.gitlab.objectStorage.endpoint }}"
      {{- end }}
      {{- if eq .Values.packages.addons.gitlab.objectStorage.type "minio" }}
      aws_signature_version: 4
      path_style: true
      {{- end }}
    registry: |-
      s3:
        {{- $global := .Values.packages.addons.gitlab.values.global | default dict }}
        {{- $registryConfig := $global.registry | default dict }}
        {{- if .Values.packages.addons.gitlab.objectStorage.bucketPrefix }}
        bucket: {{ .Values.packages.addons.gitlab.objectStorage.bucketPrefix }}-gitlab-registry
        {{- else if hasKey $registryConfig "bucket" }}
        bucket: {{ .Values.packages.addons.gitlab.values.global.registry.bucket }}
        {{- else }}
        bucket: gitlab-registry
        {{- end }}
        {{- if eq .Values.packages.addons.gitlab.objectStorage.iamProfile "" }}
        accesskey: {{ .Values.packages.addons.gitlab.objectStorage.accessKey }}
        secretkey: {{ .Values.packages.addons.gitlab.objectStorage.accessSecret }}
        {{- end }}
        {{- if .Values.packages.addons.gitlab.objectStorage.endpoint }}
        regionendpoint: "{{ .Values.packages.addons.gitlab.objectStorage.endpoint }}"
        {{- end }}
        region: {{ .Values.packages.addons.gitlab.objectStorage.region }}
        {{- if eq .Values.packages.addons.gitlab.objectStorage.type "s3" }}
        v4auth: true
        {{- end }}
        {{- if eq .Values.packages.addons.gitlab.objectStorage.type "minio" }}
        aws_signature_version: 4
        path_style: true
        {{- end }}
    backups: |-
      [default]
      {{- if eq .Values.packages.addons.gitlab.objectStorage.iamProfile "" }} 
      access_key = {{ .Values.packages.addons.gitlab.objectStorage.accessKey }}
      secret_key = {{ .Values.packages.addons.gitlab.objectStorage.accessSecret }}
      host_bucket = %(bucket)s.{{ regexReplaceAll "http(s*)://" .Values.packages.addons.gitlab.objectStorage.endpoint "" }}
      {{- end }}
      bucket_location = {{ .Values.packages.addons.gitlab.objectStorage.region }}
      multipart_chunk_size_mb = 128
{{- end }}
{{- end }}
