# Use Kyverno instead of Gatekeeper
gatekeeper:
  enabled: false
kyverno:
  enabled: true
kyvernoPolicies:
  enabled: true
  values:
    celPoliciesBeta:
      restrict-host-ports-cel:
        validationFailureAction: Audit
      restrict-capabilities-cel:
        validationFailureAction: Audit
      restrict-image-registries-cel:
        validationFailureAction: Audit
      disallow-host-namespaces-cel:
        validationFailureAction: Audit
      disallow-privileged-containers-cel:
        validationFailureAction: Audit
      require-non-root-user-cel:
        validationFailureAction: Audit
      restrict-host-path-mount-pv-cel:
        validationFailureAction: Audit
