# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
templates:
  - templates/kiali/values.yaml
postRenderer:
  cmd: "sh"
  args:
    - "-c"
    - "yq eval '.stringData.defaults' - | yq eval '.'"
tests:
  - it: make assertions on the default values for Kiali
    set:
      istiod.values.hardened.enabled: true
    asserts:
      - equal:
          path: domain
          value: "dev.bigbang.mil"
      - equal:
          path: istio.enabled
          value: true
  - it: should enable istio sidecar when kiali hardened is enabled
    set:
      kiali.values.hardened.enabled: true
    asserts:
      - equal:
          path: istio.sidecar.enabled
          value: true
  - it: should map customServiceEntries to istio.serviceEntries.custom
    set:
      kiali.values.hardened.customServiceEntries:
        - name: "test-service-entry"
          hosts:
            - "example.com"
    asserts:
      - equal:
          path: istio.serviceEntries.custom[0].name
          value: "test-service-entry"
      - equal:
          path: istio.serviceEntries.custom[0].hosts[0]
          value: "example.com"
  - it: should map customAuthorizationPolicies to istio.authorizationPolicies.custom
    set:
      kiali.values.hardened.customAuthorizationPolicies:
        - name: "test-authz-policy"
          labels:
            app: "kiali"
    asserts:
      - equal:
          path: istio.authorizationPolicies.custom[0].name
          value: "test-authz-policy"
      - equal:
          path: istio.authorizationPolicies.custom[0].labels.app
          value: "kiali"

