{{- if or .Values.packages.addons.eckOperator.enabled .Values.packages.addons.elasticsearchKibana.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: eck-operator
  labels:
    app.kubernetes.io/name: eck-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ ternary "enabled" "disabled" (and .Values.packages.core.istio.enabled (eq (dig "istio" "injection" "enabled" .Values.packages.addons.eckOperator) "enabled")) }}
{{- end }}
