{{- $mmOpOldValues := default dict .Values.packages.addons.mattermostoperator -}}
{{- $mmOpValues := mergeOverwrite $mmOpOldValues .Values.packages.addons.mattermostOperator -}}
{{- if or $mmOpValues.enabled .Values.packages.addons.mattermost.enabled }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: mattermost-operator
  labels:
    app.kubernetes.io/name: mattermost-operator
    app.kubernetes.io/component: "collaboration-tools"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}