{{- $mmOpOldValues := default dict .Values.packages.addons.mattermostoperator -}}
{{- $mmOpValues := mergeOverwrite $mmOpOldValues .Values.packages.addons.mattermostOperator -}}
{{- if or $mmOpValues.enabled .Values.packages.addons.mattermost.enabled }}
{{- include "values-secret" (dict "root" $ "package" $mmOpValues "name" "mattermost-operator" "defaults" (include "bigbang.defaults.mattermostOperator" .)) }}
{{- end }}

{{- define "bigbang.defaults.mattermostOperator" -}}
imagePullSecrets:
  - name: private-registry

image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

{{- if .Values.packages.core.istio.enabled }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end}}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ .Values.packages.core.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.mattermostOperator.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

openshift: {{ .Values.openshift }}
{{- end -}}
