{{- if and .Values.packages.addons.tempo.enabled .Values.packages.addons.tempo.objectStorage.accessKey .Values.packages.addons.tempo.objectStorage.accessSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: tempo-object-storage
  namespace: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
type: kubernetes.io/opaque
data:
    AWS_ACCESS_KEY_ID: {{ .Values.packages.addons.tempo.objectStorage.accessKey | b64enc }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.packages.addons.tempo.objectStorage.accessSecret | b64enc }}
{{- end }}
