{{- if .Values.packages.addons.tempo.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.packages.addons.tempo "name" "tempo" "defaults" (include "bigbang.defaults.tempo" .)) }}
{{- end }}

{{- define "bigbang.defaults.tempo" -}}

{{- if include "istioEnabled" . }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

objectStorage: 
  access_key_id: {{ .Values.packages.addons.tempo.objectStorage.accessKey }}
  secret_access_key: {{ .Values.packages.addons.tempo.objectStorage.accessSecret }}

tempo:
  pullPolicy: {{ .Values.imagePullPolicy }}
  global_overrides:
    ingestion_rate_limit_bytes: 30000000
{{- with .Values.packages.addons.tempo.objectStorage }}
{{- if and .endpoint .region .bucket }}
  storage: 
    trace:
      backend: s3
      s3:
        endpoint: {{ .endpoint }}
        bucket: {{ .bucket }}
        region: {{ .region }}
        insecure: {{ .insecure }}
        forcepathstyle: true
{{- end }}
{{- end }}

{{- if .Values.packages.addons.monitoring.enabled }}
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://monitoring-monitoring-kube-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
{{- end }}

# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

tempoQuery:
  pullPolicy: {{ .Values.imagePullPolicy }}

serviceAccount:
  imagePullSecrets:
    - name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  istioNamespaceSelector:
  {{ include "istioNamespaceSelector" . | nindent 4 }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}
  ingressLabels:
    {{- if .Values.packages.core.istio.enabled }}
    {{- $gateway := default "public" .Values.packages.addons.tempo.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.packages.core.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.packages.core.istio) | nindent 4 }}
    {{- end }}
    {{- if .Values.packages.core.istioCore.enabled }}
    app: public-ingressgateway
    istio: ingressgateway
    {{- end }}

istio:
  enabled: {{ include "istioEnabled" . }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.packages.addons.tempo.values)
      (dig "hardened" "enabled" false .Values.packages.core.istio.values)
    }}
  tempoQuery:
    # Set TempoQuery UI to "tempo." if Jaeger is enabled
    {{- if .Values.packages.addons.jaeger.enabled }}
    hosts:
      - "tempo.{{ .Values.domain }}"
    {{- end }}
    gateways:
    - {{ include "istioGatewayNamespace" . }}/{{ default (include "istioPublicGateway" . ) .Values.packages.addons.tempo.ingress.gateway }}

monitoring:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}

serviceMonitor:
  enabled: {{ .Values.packages.addons.monitoring.enabled }}
  # conditional passes only if all conditionals are true:
  # - istio: enabled
  # - mTLS: SCRICT
  {{- if and (include "istioEnabled" .) (eq (dig "istio" "mtls" "mode" "STRICT" .Values.packages.addons.tempo.values) "STRICT") }}
  scheme: https
  tlsConfig:
    caFile: /etc/prom-certs/root-cert.pem
    certFile: /etc/prom-certs/cert-chain.pem
    keyFile: /etc/prom-certs/key.pem
    insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
  {{- end }}

sso:
  enabled: {{ .Values.packages.addons.tempo.sso.enabled }}

{{- if or .Values.packages.addons.kiali.enabled .Values.packages.addons.tempo.sso.enabled }}
{{- $tempoAuthserviceKey := (dig "selector" "key" "protect" .Values.packages.addons.authservice.values) }}
{{- $tempoAuthserviceValue := (dig "selector" "value" "keycloak" .Values.packages.addons.authservice.values) }}
podLabels:
  {{- if .Values.packages.addons.tempo.sso.enabled }}
  {{ $tempoAuthserviceKey }}: {{ $tempoAuthserviceValue }}
  {{- end }}
{{- end }}

{{- end -}}
