name: Mirror Repository

on:
  schedule:
    - cron: '0 * * * *' # This runs the action every hour. Adjust as needed.
  workflow_dispatch: # Allows the workflow to be run manually from the Actions tab.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          repository: shebashio/bigbang
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with the original repo
        run: |
          git remote add upstream https://repo1.dso.mil/big-bang/bigbang.git || true
          git fetch upstream
          git push origin +refs/remotes/upstream/*:refs/heads/*

