{{- if .Values.alloy.enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: alloy-waypoint
{{- end }}
