{{- /* Create secret */ -}}
{{- if .Values.addons.alloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.alloy "name" "alloy" "defaults" (include "bigbang.defaults.alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.alloy" -}}

grafana:
  enabled: {{ .Values.grafana.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
  
image:
  imagePullPolicy: {{ .Values.imagePullPolicy }}

domain: {{ .Values.domain }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

{{- end }}