{{- /* Create secret */ -}}
{{- if .Values.addons.alloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.alloy "name" "alloy" "defaults" (include "bigbang.defaults.alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.alloy" -}}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}
  hardened:
    enabled: {{ or
      (dig "istio" "hardened" "enabled" false .Values.monitoring.values)
      (dig "istio" "hardened" "enabled" false .Values.addons.authservice.values)
      (dig "hardened" "enabled" false .Values.istio.values)
      (dig "istio" "hardened" "enabled" false .Values.grafana.values)
      (dig "istio" "hardened" "enabled" false .Values.loki.values)
      (dig "istio" "hardened" "enabled" false .Values.eckOperator.values)
      (dig "istio" "hardened" "enabled" false .Values.elasticsearchKibana.values)
      (dig "istio" "hardened" "enabled" false .Values.addons.mimir.values)
      (dig "istio" "hardened" "enabled" false .Values.addons.alloy.values)
    }}

k8s-monitoring:
  {{- range $service := list "alloy-metrics" "alloy-log" }} # Add/Remove Alloy Micro-Services as Alloy Configurations Change
  {{ $service }}:
    serviceMonitor:
      enabled: {{ $.Values.monitoring.enabled }}
      {{- if and (include "istioEnabled" $) (eq (dig "istio" "mtls" "mode" "STRICT" $.Values.addons.alloy.values) "STRICT") }}
      tlsConfig:
        caFile: /etc/prom-certs/root-cert.pem
        certFile: /etc/prom-certs/cert-chain.pem
        keyFile: /etc/prom-certs/key.pem
        insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
      {{- end }}
  {{- end }}

  destinations:
    {{- if .Values.monitoring.enabled }}
    - name: metricsServicePrometheus
      type: prometheus
      url: http://monitoring-monitoring-kube-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
      metrics:
        enabled: true
      logs:
        enabled: false
      traces:
        enabled: false
    {{- end }}
    {{- if .Values.addons.mimir.enabled .Values.alloy.alloy-metrics.enabled }}
    - name: metricsServiceMimir
      type: prometheus
      url: https://mimir-mimir-gateway.mimir.svc.cluster.local:80/api/v1/push
      metrics:
        enabled: true
      logs:
        enabled: false
      traces:
        enabled: false
    {{- end }}
    {{- if .Values.loki.enabled .Values.alloy.alloy-logs.enabled }}
    - name: logsServiceLoki
      type: loki
      url: logging-loki.logging.svc.cluster.local:3100/loki/api/v1/push
      metrics:
        enabled: false
      logs:
        enabled: true
      traces:
        enabled: false
    {{- end }}
    {{- if .Values.tempo.enabled .Values.alloy.alloy-receiver.enabled }}
    - name: tracesServiceTempo
      type: otlp
      metrics:
        enabled: false
      logs:
        enabled: false
      traces:
        enabled: true
      url: tempo-tempo.tempo.svc.cluster.local:4317
      tls: {}
    {{- end }}
{{- end }}