{{- /* Create secret */ -}}
{{- if .Values.addons.alloy.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.alloy "name" "alloy" "defaults" (include "bigbang.defaults.alloy" .)) }}
{{- end }}

{{- define "bigbang.defaults.alloy" -}}
monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

{{- if (or .Values.addons.alloy.disable-reporting  .Values.addons.alloy.extraArgs) }}
extraArgs:
{{- if .Values.addons.alloy.disable-reporting  }}
- --disable-reporting
{{- end }}
{{- range .Values.addons.alloy.extraArgs }}
- {{ . }}
{{- end }}
{{- end }}

{{- end }}