{{- $fluxSettingsAuthservice := merge .Values.packages.addons.authservice.flux .Values.flux -}}
{{- if and (include "istioEnabled" .) (or .Values.packages.addons.authservice.enabled (and .Values.packages.addons.monitoring.enabled .Values.packages.addons.monitoring.sso.enabled) (and .Values.packages.addons.jaeger.enabled .Values.packages.addons.jaeger.sso.enabled) (and .Values.packages.addons.tempo.enabled .Values.packages.addons.tempo.sso.enabled)) }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authservice
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: authservice
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/authservice/values.yaml") . | sha256sum }}
spec:
  targetNamespace: authservice
  chart:
    spec:
      {{- if eq .Values.packages.addons.authservice.sourceType "git" }}
      chart: {{ .Values.packages.addons.authservice.git.path | default "./chart" }}
      sourceRef:
        kind: GitRepository
        name: authservice
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.packages.addons.authservice.helmRepo.chartName }}
      version: {{ .Values.packages.addons.authservice.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.packages.addons.authservice.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.packages.addons.authservice.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.packages.addons.authservice.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.packages.addons.authservice.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsAuthservice | nindent 2 }}

  {{- if .Values.packages.addons.authservice.postRenderers }}
  postRenderers:
  {{ toYaml .Values.packages.addons.authservice.postRenderers | nindent 4 }}
  {{- end }}

  valuesFrom:
    - name: {{ .Release.Name }}-authservice-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-authservice-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-authservice-values
      kind: Secret
      valuesKey: "overlays"

  dependsOn:
  {{- if .Values.packages.core.istio.enabled }}
  - name: istio
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.addons.monitoring.enabled }}
  - name: monitoring
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.packages.core.istioCore.enabled }}
  - name: istio-core
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
