{{- if and (include "istioEnabled" .) (or .Values.packages.addons.authservice.enabled (and .Values.packages.addons.monitoring.enabled .Values.packages.addons.monitoring.sso.enabled) (and .Values.packages.addons.jaeger.enabled .Values.packages.addons.jaeger.sso.enabled) (and .Values.packages.addons.tempo.enabled .Values.packages.addons.tempo.sso.enabled)) }}
{{- if ( include "imagePullSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: authservice
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}